### ISSUE TITLE
Alternative Minion Pro Font Download Option

### ISSUE THREAD

**Issue by nickv2002** [sumpfork/dominiontabs#100]
A website called FontsGeek is offering downloads of Minion Pro: [Regular](http://fontsgeek.com/fonts/Minion-Pro-Regular), [Bold](http://fontsgeek.com/fonts/Minion-Pro-Bold), and [Italic](http://fontsgeek.com/fonts/Minion-Pro-Italic)

These files still need to be run through `./convert.ff` (I handled the FontForge dependency with HomeBrew on my Mac) and they need slight renaming to match the file names expected by the script. However, it's an easier option than extracting them from an install of Adobe Reader.

@sumpfork are you okay with us providing a link to this on the front page?

**Comment by sumpfork** [comment]
Yes. We should check whether there's more to find out about the distribution status of Minion Pro - fontgeek clearly thinks it's freely distributable (and doesn't include an owner/copyright notice), in which case we could probably just do the same.

**Comment by sumpfork** [comment]
See #122 and #132.
