### ISSUE TITLE
Allow for grouping of additional setup cards (i.e. 'Page Upgrades', 'Prizes')

### ISSUE THREAD

**Issue by marksim** [sumpfork/dominiontabs#11]
In order to properly get the back-and-forth tabs working, we need to have the option to leave out all the page and peasant upgrades as well as tournament prizes and mercenary / madman -- basically an option to treat all cards that are *not* normally in the supply as a separate set would do, but making it such that all page upgrades were lumped together, etc would also be nice.

**Comment by sumpfork** [comment]
I think this has been implemented by 473b35e66792db380bdcbbcbb0e61dbefa09ae91, correct? It's not exposed on the generator site yet.
