### ISSUE TITLE
Choosing sets

### ISSUE THREAD

**Issue by sorawotobu** [sumpfork/dominiontabs#110]
Base has no cards. Dominion includes the base cards. Empires has no cards.

**Comment by wvoigt** [comment]
By design, Dominion includes the base cards.
For the others, can you please add more information on this issue.   My testing does not show this.  What options are you using?

**Comment by sorawotobu** [comment]
Settings I used:
Expansions to include: Dominion, Empires, Adventures, Seaside
Divider Orientation: Horizontal
Page Size: A4
Card Size: Sleeved
Tab side: centre
Tab name align: centre
Set Icon Location: tab
Cost Icon Location: tab
Front Text: blank
Back Text: no back page
language: Deutsch
checked boxes: Group by Expansion & Group Special Cards (e.g. Prizes)

Not including the base cards in "Dominion" gives people strictly more options, some people might for example already have base card dividers on account of having purchased the Base Cards set and only got the base set later, so they wouldn't want to print out the base card dividers again. You could rename "Dominion" to "Dominion (does not include base cards)" so people don't get confused.

If I use different settings, i.e. not selecting "Dominion" but selecting "Base", I don't get base cards. Even if you don't agree that "Dominion" shouldn't include base cards, surely you agree that "Base" should include the base cards. And yeah, no dividers for any "Empires" cards.

**Comment by sumpfork** [comment]
I believe this is all addressed with the new deployment - please re-open if not.
