### ISSUE TITLE
"Group special cards" doesn't work for travellers

### ISSUE THREAD

**Issue by sorawotobu** [sumpfork/dominiontabs#112]
This used to work for the Page line before the 11/14 update. Now it doesn't. Does not and did not work for Peasant.

**Comment by wvoigt** [comment]
Can you please give the options you are using for this.   I'm not seeing this issue.

**Comment by sorawotobu** [comment]
Settings I used:
Expansions to include: Dominion, Empires, Adventures, Seaside
Divider Orientation: Horizontal
Page Size: A4
Card Size: Sleeved
Tab side: centre
Tab name align: centre
Set Icon Location: tab
Cost Icon Location: tab
Front Text: blank
Back Text: no back page
language: Deutsch
checked boxes: Group by Expansion & Group Special Cards (e.g. Prizes)

This gives me separate dividers for each Page/Peasant upgrade.

side note: capitalization in the options is inconsistent

**Comment by sumpfork** [comment]
I believe this is fixed with the new deployment - please re-open if not.
