### ISSUE TITLE
Add a command option to include a page in the pdf with the options used

### ISSUE THREAD

**Issue by wvoigt** [sumpfork/dominiontabs#120]
Since it can be months between printing/generating dividers, it would be nice to have a way to help remember the options used to get a particular output.

Presumably as the last page.
Hopefully formatted nicely.
Possibly with a list of all the options possible (i.e., --help)

**Comment by wvoigt** [comment]
First try at this is in Pull #150

**Comment by wvoigt** [comment]
Instead of making this a part of the draw refactor, I just put the changes for this issue into a separate Pull request #198

**Comment by sumpfork** [comment]
Sure, if you have the time. I'm off to Germany for the next two weeks, so there's a chance that between visiting and taking care of kids I'll have a chance to finally get to land some of your PRs :).

**Comment by sumpfork** [comment]
Done with #198, release pending.
