### ISSUE TITLE
Add an option to download/copy convert fonts and install them with standardized names

### ISSUE THREAD

**Issue by sumpfork** [sumpfork/dominiontabs#122]
See #100 for download and the copy could happen from Adobe Reader installs if they exist.

**Comment by nickv2002** [comment]
FontsGeek download has captcha otherwise we could automate it… but we could have it look for 3 zip files in the working directory and do the rest.

**Comment by sumpfork** [comment]
Given the inability to download from fontsgeek programmatically and the difficulty of tracking Adobe Reader installs I think we'll just leave this as is. I added a note about the fontsgeek copies to the README in #131. This is a one time operation only needed to run from source, and the script works without it with just slightly different looking output, so I think it's not worth a major effort.
