### ISSUE TITLE
German: Missing cards/Traveller mess

### ISSUE THREAD

**Issue by idlaviV** [sumpfork/dominiontabs#128]
Hi,

If I choose german language, some problems occure in Adventures and Empires.
*There are no dividers for landmarks in Empires and Events in both
*The travellers are wrong:
There is a (Peasant) divider, (Soldier), (Fugitive), (Disciple), (Teacher), a (Page-->Champion) divider, (Treasure Hunter), (Warrior), (Hero), So there is some inconsistency going on: I guess you want a common divider for each of the both lines or you want everything divided.

**Comment by nickv2002** [comment]
@idlaviV Was this using the web interface or the code from this site?  If code please also let us know which branch. Thanks.

**Comment by idlaviV** [comment]
This was the web interface.

**Comment by nickv2002** [comment]
@idlaviV okay, we've got a new build in the works that significantly restructures how things like dividers and travelers work and I'm willing to bet it will solve the issues you list. It's actually all done (in English) we're just waiting for @sumpfork to have time to deploy it on the web. You can [check it out here](https://github.com/sumpfork/dominiontabs/tree/Card-DB-refactoring) right now.

Also, we could use help with translations of new cards to German, you don't need to know how to code, it's just translation and following the right format.

**Comment by sumpfork** [comment]
I believe a good chunk of this is addressed with the new deployment. Please open new issues for remaining problems.
