### ISSUE TITLE
Page and Peasant Cost

### ISSUE THREAD

**Issue by sumpfork** [sumpfork/dominiontabs#13]
From BGG thread comment: Found an error just now with the Adventures tabs - the upgrades to Page and Peasant should have an asterisk in their cost.

**Comment by selfthinker** [comment]
It seems only Prizes have an asterisk in their cost. It is also missing on Peddler and Spoils.
All the pluses are missing from various Guilds cards as well.

**Comment by sumpfork** [comment]
Agreed, asterisk option was not available before and the card db needs a pass to add them.

**Comment by sumpfork** [comment]
Thanks! Merged and deployed to online generator.
