### ISSUE TITLE
DividerDrawer.add_inline_images issue with new package format

### ISSUE THREAD

**Issue by wvoigt** [sumpfork/dominiontabs#134]
@sumpfork 
In Make better package (#132), an error was introduced.

```
replace = '<img src=' "'{}'" ' width={} height=' "'100%'" ' valign=' "'middle'" '/>'
replace = replace.format(DividerDrawer.get_image_filepath('coin_small_1.png'), fontsize * 1.2)
text = re.sub('(\d+)\s(c|C)oin(s)?', replace, text)
```

before this was:

```
path = os.path.join(self.options.data_path, 'images')
. . .
replace = '<img src=' "'%s/coin_small_\\1.png'" ' width=%d height=' "'100%%'" ' valign=' "'middle'" '/>'
replace = replace % (path, fontsize * 1.2)
text = re.sub('(\d+)\s(c|C)oin(s)?', replace, text)
```

The new code always picks `coin_small_1.png`.  The original code picked the `coin_small_x.png` where x was the number matched by (\d+).

Similar problem for the large coin and in debt section.

Other (dumb, newbie) questions:
1. Is there a reason it is called as `DividerDrawer.get_image_filepath` instead of `self.get_image_filepath`?
2. From a development standpoint, how are you running the program locally now.  I really don't want to have to install the package every time I make a change.  I prefer the "make a change an run" approach.  Is there a way to run this without installing it as a package?  I've been trying a local script in my own 'mytest' directory (at the same level as 'domdiv') called `dominion_dividers.py` that is simply:

```
import sys
import os

script_path = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))

if script_path not in sys.path:
    sys.path.insert(0, script_path)
    
os.chdir(script_path)

from domdiv import main

options = main.parse_opts()
main.generate(options)
```
It works for --help, but when generating an actual file, I'm getting an error (with an image filename) which brought me to the above problem.  But I don't think it is related.

**Comment by sumpfork** [comment]
Use `python setup.py develop` and the `dominion_dividers` script it installs to run locally - it puts your dev version of the code on the python path, so you can test as you code.

I'll address the other stuff in a bit.

**Comment by sumpfork** [comment]
Ok, #135 should address the main issue here, thanks for spotting that. The solution did require a bit more of a rewrite.

As for `DividerDrawer.get_image_filepath` - I like to do this for static methods to signal that that's what's happening (no `self` is actually passed in). Not a big deal to use `self` instead, though

**Comment by wvoigt** [comment]
Dang, just found a problem.  Not sure why.   Some seem to work, but others do not.
Look at "Giant" in Adventures.   Everything is 1 coin.  

![image](https://cloud.githubusercontent.com/assets/1182468/21279396/a662515e-c3a5-11e6-96e8-32fdebd4d03c.png)
The text is:
`"Turn your Journey token over (it starts face up). If it's face down, +1 Coin. If it's face up, +5 Coins, and each other player reveals the top card of his deck, trashes it if it costs 3 Coins to 6 Coins, and otherwise discards it and gains a Curse."`

But the back of "Messenger" is OK
![image](https://cloud.githubusercontent.com/assets/1182468/21279428/ce431172-c3a5-11e6-84a6-19c2300508d9.png)
The text is:
`"When you play this, you get +1 Buy, + 2 Coin , and may optionally put your deck into your discard pile. This is not discarding cards and does not trigger Tunnel (from Hinterlands). When you buy Messenger, if it is the first thing you bought that turn (card or Event), you gain a card costing up to 4 Coins from the Supply, putting it into your discard pile, and then each other player in turn order also gains a copy of that card. If the Supply runs out of copies of the card, further players do not get anything."`

**Comment by sumpfork** [comment]
Messenger isn't ok either - notice the 2 instead of 4. I think I'm not re-replacing on each instance or something...

**Comment by sumpfork** [comment]
Try now, after b6054ed6bbb194fd8acad4fd871de2e586689ef1?

**Comment by wvoigt** [comment]
Yes, that seems to work.
