### ISSUE TITLE
Second Edition Consistency & Clarity Updates

### ISSUE THREAD

**Issue by nickv2002** [sumpfork/dominiontabs#136]
Apparently the [Hinterlands Rules PDF](http://riograndegames.com/getFile.php?id=579) has been updated with new card wordings.

For example for _Oracle_:

Old:
> Each player (including you) reveals the top 2 cards of his deck, and you choose one: either he discards them, or he puts them back on top in an order he chooses.
> **+2 Cards**

New:
> Each player (including you) reveals the top 2 cards of their deck, and discards them or puts them back, your choice. They choose the order to return them. Afterwards, you draw 2 cards.

We should double check the Card DB for consistent wording.

**Comment by nickv2002** [comment]
See [DominionStrategy Wiki Updates](http://wiki.dominionstrategy.com/index.php?namespace=0&title=Special%3ARecentChanges) on & around December 16, 2016.

**Comment by nickv2002** [comment]
I won't have time to get to this in December, but I'll try in January.  There might be other sets with revised wordings in the future too…

**Comment by nickv2002** [comment]
Prosperity has had a editor pass on it, here's [the updated rulebook PDF](http://riograndegames.com/getFile.php?id=517)

[According to this](https://boardgamegeek.com/blogpost/64531/new-game-round-chimera-reborn-colonists-rerun-and), Seaside is next to get a second pass for rules clarity and consistency.

I'll get to these edits someday. 😄

**Comment by sumpfork** [comment]
I think most of this was done with #276 and #346 - closing in favour of more specific new issues.
