### ISSUE TITLE
dominion_tabs.py fails: ImportError: No module named yaml

### ISSUE THREAD

**Issue by splatteredbits** [sumpfork/dominiontabs#14]
When I try to run 

    > python dominion_tabs.py -h

I get:

> Traceback (most recent call last):
>  File "dominion_tabs.py", line 15, in <module>
>    import yaml
> ImportError: No module named yaml

I'm running Mac OS X Yosemite. I'm a software developer, but have never used Python before so don't know how to get this module installed. I tried running `pip install yaml`, `pip install python-yaml`, but neither worked.

I expected that `pythong setup.py install` would have installed all needed dependencies. Please update setup.py so it installs the yaml module.

**Comment by nickv2002** [comment]
You should try `pip install pyyaml` (or perhaps `sudo -h pip install pyyaml`) on your system.  That should take care of this requirement.

**Comment by sumpfork** [comment]
I think this is a reasonable expectation considering there's a setup.py. I added PyYAML to it in a recent commit.
