### ISSUE TITLE
Show both costs for split piles

### ISSUE THREAD

**Issue by JesseMFrey** [sumpfork/dominiontabs#143]
For split piles (Empires) each card generally has a different cost. dominiontabs only shows one cost (the top card I think). It would be nice if both were shown

**Comment by wvoigt** [comment]
Split piles is just one example of grouping.  There is also the travellers, and they have 5 different costs. That could get quite long.

So after a discussion during the last major update, a design decision was made to use the cost value shown on the randomizer card. At this point it would take a large update to the data structure to implement more than one cost.

**Comment by JesseMFrey** [comment]
That makes sense. On the "organizing inlay" provided with empires it shows both coasts for split piles so that was what I was expecting to see. I don't look at the randomizers much.

**Comment by nickv2002** [comment]
This is very much a sky-pie feature so I'm closing the issue but labeling it for future reference.
