### ISSUE TITLE
Extra Expansion Dividers Misprint

### ISSUE THREAD

**Issue by fifguy85** [sumpfork/dominiontabs#145]
If you select Front Text = Rules and Back Text = Card, then on the Extra Expansion dividers the card list is printed upside down on the front and the title of the set that should be on the back is instead also upside down on the front.

See on the last page of the example PDF attached here.

[sumpfork_dominion_tabs.pdf](https://github.com/sumpfork/dominiontabs/files/743896/sumpfork_dominion_tabs.pdf)

**Comment by wvoigt** [comment]
Yes, slipcase backside text and tab is shifted by a divider height, so it looks like it is on the front of the divider. I'll work a fix for it.

**Comment by wvoigt** [comment]
Created Pull Request #147 to fix this issue.

**Comment by wvoigt** [comment]
This was fixed as of Pull #147 and is contained in v3.2.1 on the website.  So closing.
