### ISSUE TITLE
Sleeved Slipcases are not deep enough

### ISSUE THREAD

**Issue by fifguy85** [sumpfork/dominiontabs#146]
The sleeved vs unsleeved options properly account for increased area of the slipcases to hold the sleeved cards, but don't account for an increased thickness of the stack of cards. This is most noticeable on the base card stacks (e.g.: Copper) since there are many more of them.

Can the generator be updated to add additional thickness/depth on the "Slipcases"/"Sleeved" option between the creases on the bottom and top of the slipcases to account for increased thickness of the sleeved card? This will result in a "taller" slipcase overall on the PDF. 

Using the numbers from Mayday sleeves site: Premium sleeves = 0.09mm/sleeve and, Standard sleeves = 0.04mm/sleeve. This would result in a minimum increase of 0.4mm for a normal 10-card kingdom card stack with standard sleeves, but a maximum of 5.4mm on the Copper stack with Premium sleeves. One idea would be to break the "Sleeved" option into two options: Sleeved (Premium), Sleeved (Standard) and rounding up to 0.1mm and 0.5mm / card to account for the slightly different thicknesses of different sleeves, but it's possible you could just split the difference between them and it would be close enough.

**Comment by wvoigt** [comment]
The support for this is already built into the python generator.  From the help:
```
  --thickness THICKNESS
                    Thickness of a stack of 60 cards (Copper) in centimeters. 
                    Typically unsleeved cards are 2.0, thin sleeved cards are 2.4,
                    and thick sleeved cards are 3.2.
                    This is only valid with the --wrapper option. (default: 2.0)
  --sleeved_thick   Same as --size sleeved --thickness 3.2. (default: False)
  --sleeved_thin    Same as --size sleeved --thickness 2.4. (default: False)
```
The real work here is bringing this out to the web interface.

**Comment by sumpfork** [comment]
Added here: https://github.com/sumpfork/bgtools_web/issues/4#issuecomment-277397380
