### ISSUE TITLE
Prosperity rules text running over onto other cards.

### ISSUE THREAD

**Issue by novarren** [sumpfork/dominiontabs#155]
When you select "rules" for both Front Text and Back Text, the VP icons run off the right side on Bishop and Monument to print on the adjoining card.

Setting the Set Icon Location to "body-top" causes the Goons rules text to behave similarly. Attached is a PDF illustrating this.
[VP_overrun.pdf](https://github.com/sumpfork/dominiontabs/files/856000/VP_overrun.pdf)

**Comment by wvoigt** [comment]
I put in a fix that helps this issue.  See Pull #156 

Fundamentally I think there is an issue with either the reportlab paragraph wrap function, or there is an issue with the image.  I looked at all the cards (in English) and there are several examples of the coins, potions, and debt images ending at the edge of a paragraph and they render fine.  Only a few cases of the VP image has problems.   With the `&thinsp;` deleted, it at least brings in the errant VP image to within the boundaries of the card.  These are the examples after the fix.

![image](https://cloud.githubusercontent.com/assets/1182468/24581885/ba6ca0d6-16e9-11e7-9823-3d5aed349a5c.png)

![image](https://cloud.githubusercontent.com/assets/1182468/24581888/cf60d214-16e9-11e7-919f-48d052f25224.png)

![image](https://cloud.githubusercontent.com/assets/1182468/24581891/daee3c7a-16e9-11e7-8739-ec9c1a36c252.png)

**Comment by wvoigt** [comment]
This was fixed as of Pull #156 and is contained in v3.2.1 on the website.  So closing.
