### ISSUE TITLE
extended labels

### ISSUE THREAD

**Issue by datcomputerguy** [sumpfork/dominiontabs#159]
I would like to work on/request a feature that would be an accompaniment of the Avery 5167/8867 option.  Basically I have some plastic cards I am using for dividers and I am using the Avery 5167/8867 labels to label the top of the plastic divider, but I would like to generate stickers similar to the print and cut out cards with the additional information on them like the description, the count, text on the card, etc.  All off that information is already generated using the script, I just want to make it align with some other Avery stickers.  I am experienced in python and I was basically looking to see if anyone else was interested in this that could help point me to where I need to focus in the code.  I have read some of the code, but it's not very clear where this code should go.

**Comment by sumpfork** [comment]
Am I understanding correctly that you want to produce labels that do not include the tabs, just the body text front and back?

Look at how Avery labels are currently produced, namely the [`tabs_only` option](https://github.com/sumpfork/dominiontabs/search?utf8=✓&q=tabs_only&type=). One way to do what you want to do is to add another option that's something like `no_tabs` (or rename the `tabs_only` option to something like `component_selection` with values `TABS_AND_DIVIDERS`, `TABS_ONLY`, `DIVIDERS_ONLY`. And for `no_tabs` (or `DIVIDERS_ONLY`) you adjust the margins and sizes to be suitable to your Avery labels and skip the `self.drawTab` call.

**Comment by wvoigt** [comment]
If the dividers don't have cut out tabs (i.e., they are pretty much taller versions of the cards), then you can get away with just adjusting the margins and sizes.   Just use:

- `--tab_side full` so the tabs go all the way across the top
- `--linewidth 0`, to not print out the outline
- `--size #x#`, for the size of the stickers
- `--minmargin #x#`, for the margin (the horizontal and vertical distance to the first label). 
- `--vertical_gap #`, for vertical gap between stickers on the page
- `--horizontal_gap #`, for horizontal gap between stickers on the page

All the #'s can be floating point numbers.

**Comment by sumpfork** [comment]
I think @wvoigt is right that you can get pretty close already. Closing this for now, feel free to reopen if somehow what you want isn't covered.
