### ISSUE TITLE
Add Cards for Dominion: Nocturne

### ISSUE THREAD

**Issue by nickv2002** [sumpfork/dominiontabs#162]
New expansion coming in October 2017.

[BoardGameGeek Listing](https://boardgamegeek.com/boardgameexpansion/232452/dominion-nocturne)

Donald X's Description:
> You've always been a night person; lately you've even considered becoming a vampire. There are a lot of advantages: you don't age; you don't have to see yourself in mirrors anymore; if someone asks you to do something, you can just turn into a bat, and then say, sorry, I'm a bat. There are probably some downsides though. You always think of the statue in the town square that came to life and now works as the tavern barmaid. The pedestal came to life, too, so she has to hop around. The village blacksmith turns into a wolf whenever there's a full moon; when there's a crescent moon, he turns into a chihuahua. That's how this stuff goes sometimes. Still, when you breathe in the night air, you feel ready for anything.
> 
> Dominion: Nocturne, the 11th expansion to Dominion, has 500 cards, with 33 new Kingdom cards. There are Night cards, which are played after the Buy phase; Heirlooms that replace starting Coppers; Fate and Doom cards that give out Boons and Hexes; and a variety of extra cards that other cards can provide.

Sounds like we'll have a few new cards types to work with here.

**Comment by nickv2002** [comment]
Previews have started. Looks like we'll need a new _Night_ category:
https://dominionstrategy.com/2017/10/23/nocturne-previews-1-devils-workshop-raider-ghost-town/

**Comment by wvoigt** [comment]
I've started a branch called Nocturne-Dismantle to hold the changes for both Nocturne and Dismantle.

**Comment by wvoigt** [comment]
So how do we want to handle the Boons, Hexes, and States?  For now, I just created a special group for them.  So with `--special_card_groups` they combine into a tab for Boons, Hexes, and States.  Without it, they print individually.  The only question is if we need to treat them like Events and Landscapes.  I guess it depends if there is ever any more of them, or if there are promo versions of them.

**Comment by wvoigt** [comment]
The following cards are listed in the [card list](https://dominionstrategy.com/nocturne-card-list/) as being included in Nocturne, but I could not find a description of these cards in any of the previews.
For the moment, I have added blank entries in the `cards_en_us.json` file, but they are not included in the `cards_db.json`

- Bard
- Changeling
- Cobbler
- Conclave
- Den of Sin
- Guardian
- Monastery
- Night Watchman
- Sacred Grove
- Secret Cave
- Tormentor
- Tracker
- Tragic Hero

**Comment by nickv2002** [comment]
Thanks @wvoigt 

Based on Dominion history there's a decent chance of more Boons/Hexes/States someday.

FWIW: I was planning to do all the text processing to get the full `cards_en_us.json` set up with rules and descriptions once all of them are available.

**Comment by wvoigt** [comment]
@nickv2002, while I've added all the text from the cards that have been previewed, all the "extra" rules still need to be added.  So there is still a lot to do.  I also only have place holders for all the image files.  Those need to be done as well.

**Comment by wvoigt** [comment]
As a reminder, once everything is done with the `en_us` files, we will run `/tools/update_language.py` to pretty up all the files (e.g., alphabetize) and then add the new text to all the other language files.

**Comment by wvoigt** [comment]
For card groupings, there is the obvious Boons, Hexes, and States.  So far I have implemented groupings where the Heirlooms are grouped with the card that brings them into the game.  And there are a few obvious pairs like Vampire / Bat. 
The ones I am struggling with are the Spirits.  They are paired with cards (one a Heirloom), but it looks like there is at least one card that lets you pick from any of them.  So I think the grouping might be to have all the Spirits together.  In the end, I think it depends upon the setup wording in the instructions (which we don't have yet.)  Or it may be we can't group them.

**Comment by wvoigt** [comment]
Also, I've added the Flavor text for the set on the back of the Expansion divider cards.  All that blank space could not go to waste :-)   Another option would be to try and get the image for the expansion there.  But that would take more to implement.  The text was a natural extension of "normal" explanation text on the back side.

**Comment by nickv2002** [comment]
Yeah, I think all Spirits will go in for certain cards in a Kingdom (pending rulebook confirmation).

Expansion divider flavor text is a nice little touch.

**Comment by nickv2002** [comment]
[Full PDF of rules with new cards](http://riograndegames.com/getFile.php?id=2093)

[Summary of cards that weren't previewed.](https://dominionstrategy.com/2017/11/16/dominion-nocturne-card-list-rules-up-and-online-now/)

I'll work on adding some of these new cards in.

**Comment by nickv2002** [comment]
I added the additional cards new cards quickly under https://github.com/sumpfork/dominiontabs/commit/9180d8d822d8711d2afd880d5d9693a19b410b49 but didn't have time to test output. I'm sure all this could use an edit pass too.

Also we might need some new header graphics for Night cards (or Night cards combined with other types). Usually we pull that from a scan of the box insert between the card. I can photoshop that up but don't have a physical copy or scanner so if someone can upload a good scan that would help.

**Comment by abjugard** [comment]
Nice, is that all of them? Been waiting for these to appear since I'm putting together a nice little box with all the expansions in it and it's pretty expensive to order a print like this.

**Comment by sumpfork** [comment]
Hey @nickv2002, can you just make a PR with that and we can review/test that way? Thanks!

**Comment by nickv2002** [comment]
@sumpfork sorry I haven't done that yet. I wanted to add all the rules text from the PDF manual but have been busy with other stuff.

**Comment by wvoigt** [comment]
I added the card rules and a set of images.  You can see them in Pull Request #171.  
Not sure if the images are of the same quality as in the past, so they should be reviewed.  If they are OK, I *think* we have about all of it in en_us.
It could use a total review.  Card texts, card counts, card types, card groupings, etc.

**Comment by arishipshape** [comment]
Hello! I have no idea what you are talking about, but I know that it is making dominion nocturne dividers! So thank you! Good job! I am going to use them! You are doing great I think!

**Comment by sumpfork** [comment]
#171
