### ISSUE TITLE
JQuery fails to load on website - can't click to expand categories

### ISSUE THREAD

**Issue by Bobthemagicmoose** [sumpfork/dominiontabs#164]
I have tried on Chrome for windows and android and both had trouble. When looking at the console it says:

`Failed to find a valid digest in the 'integrity' attribute for resource 'https://code.jquery.com/jquery-3.2.1.min.js' with computed SHA-256 integrity 'hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4='. The resource has been blocked.`

**Comment by Bobthemagicmoose** [comment]
It loads fine with Microsoft Edge.

**Comment by sumpfork** [comment]
What was the original browser you used that failed?

**Comment by iburton** [comment]
Can confirm @Bobthemagicmoose has identified the issue.  It does work in my IE Edge as well, my guess is that it does not check the hash like it should.

**Comment by sumpfork** [comment]
Fixed, see sumpfork/bgtools_web#8
