### ISSUE TITLE
New Dismantle Promo

### ISSUE THREAD

**Issue by nickv2002** [sumpfork/dominiontabs#165]
New German promo called "Abbruch" likely will be Dismantle in English:

> 4$ Action
> Trash a card from your hand. If it costs 1$ or more, gain a cheaper card and a Gold.

http://dominionstrategy.com/2017/10/23/new-german-dominion-promo-abbruch/

**Comment by wvoigt** [comment]
I've started a branch called Nocturne-Dismantle to hold the changes for both Nocturne and Dismantle.

**Comment by sumpfork** [comment]
PR #171
