### ISSUE TITLE
Sorting with accented characters (French card names) is not correct

### ISSUE THREAD

**Issue by rmammouth** [sumpfork/dominiontabs#168]
When using French card names, accented characters are placed after Z, which is not correct.
For instance in Hinterlands, Écuries (Stables) should not appear as the last card, but between Develop(pement) and Mandarin.
This might help : https://stackoverflow.com/questions/4409009/sorting-strings-with-accented-characters-in-python

**Comment by sumpfork** [comment]
Fixed with #169
