### ISSUE TITLE
cards.yaml missing Adventures cards

### ISSUE THREAD

**Issue by achapp** [sumpfork/dominiontabs#18]
It looks like the Adventures card set was only added to dominion_cards.txt and dominion_card_extras.txt, so the yaml database doesn't have these cards.

**Comment by sumpfork** [comment]
I re-generated the yaml from the .txt files - this needs to be consolidated and the yaml made the authoritative source at some point, but I'm still debating whether the current serialization approach or a more explicit yaml save/load without indication of python types would be better.
