### ISSUE TITLE
Wish should be its own pile

### ISSUE THREAD

**Issue by nickv2002** [sumpfork/dominiontabs#183]
Report via: https://boardgamegeek.com/article/27712681#27712681
> When grouping special cards, you have "Leprechaun/Wish". However, Wish can also be gained via Magic Lamp (which is only when Secret Cave is in play). So to my understanding, even when grouping cards, Leprechaun and Wish should be separated, like the Spirits.

This is true: I gained a Wish with a Magic Lamp the other day (though I think Leprechauns were in the game too).

Super busy with other stuff now so no time to fix. 😞

**Comment by sumpfork** [comment]
#186
