### ISSUE TITLE
Online generator is down, 502 Bad Gateway

### ISSUE THREAD

**Issue by samlindsaylevine** [sumpfork/dominiontabs#188]
I'm a very satisfied user of your online tab generator who just bought Nocturne and was looking to go generate some more tabs to match the rest of my storage!

Unfortunately, it looks like the online generator as linked in the main README.md - http://domtabs.sandflea.org/ - is down. It's responding with a 502 Bad Gateway error.

**Comment by sumpfork** [comment]
Back up - though I should make that automatic - https://github.com/sumpfork/bgtools_web/issues/13

**Comment by samlindsaylevine** [comment]
Thanks again! I appreciate the work you've done in making the generator available to us all!
