### ISSUE TITLE
domtab is offline

### ISSUE THREAD

**Issue by idlaviV** [sumpfork/dominiontabs#194]
Atm, I'm not able to reach http://domtabs.sandflea.org/. I get 
502 – Bad Gateway

The page you requested is currently unavailable. Please try again later.

If you are the website owner, please see Error: 502 Bad Gateway documentation for more information and possible steps to resolve the problem.

**Comment by openam** [comment]
It appears to be working now.

**Comment by idlaviV** [comment]
Indeed.
