### ISSUE TITLE
Unsleeved horizontal A4 sheets overlap with expansion name

### ISSUE THREAD

**Issue by UrbanSpaceman** [sumpfork/dominiontabs#20]
Running from http://domtabs.sandflea.org/ using A4, horizontal, unsleeved means the bottom pair of dividers overlaps the expansion name at the bottom of the page.
![a4unsleevedhorizontal-faulty](https://cloud.githubusercontent.com/assets/13681897/9117936/476993e2-3c65-11e5-9a91-983e360e7b48.png)

**Comment by UrbanSpaceman** [comment]
Note, that this only happens when "Group by Expansion" is selected.

**Comment by sumpfork** [comment]
At minimum I've exposed the already existing option to not print the footers on the generator page now, so at least it's possible to print in this format and order. The overlap should still be fixed, obviously.

**Comment by sumpfork** [comment]
I played with this a bit, too, and agree that it doesn't currently seem possible to make the vertical open kick in. Your fixes look good otherwise, just fixed a pep8 thing.
