### ISSUE TITLE
UK Avery labels

### ISSUE THREAD

**Issue by jeremyscode** [sumpfork/dominiontabs#200]
Unfortunately it's almost impossible to get the 8867 labels in the UK for a reasonable price. Is there any chance you could add an option for the UK version? I don't mind testing it for you, I'd imagine the online template designer would provide enough detail for coding it in theoretically. I'll let you know if it works. Link here https://www.avery.co.uk/product/mini-multipurpose-labels-l4732rev-25

**Comment by sumpfork** [comment]
This is landed, but needs to be integrated with the online generator.
