### ISSUE TITLE
Change background colour of avery labels to black

### ISSUE THREAD

**Issue by Sunthief** [sumpfork/dominiontabs#203]
Would be awesome to be able to make the background black instead of white for people that use black dividers, such as I.

**Comment by sumpfork** [comment]
https://github.com/sumpfork/dominiontabs/tree/black_avery_background has the code for this. The main thing that needs to happen for this to look good is to fix the alpha on the images, mainly where' it's white instead of transparent. The newer ones are mostly ok, but old ones need some love.

**Comment by wvoigt** [comment]
I added transparent backgrounds to banners.  I think I got all of them.  If I didn't, just let me know.

**Comment by sumpfork** [comment]
PR #217

**Comment by sumpfork** [comment]
Do you need this added to the web generator, or can you use the script itself @Sunthief?

**Comment by sumpfork** [comment]
Ok, I exposed the option on the web generator under 'Global Options'.

**Comment by Sunthief** [comment]
Awesome, thanks a lot!
