### ISSUE TITLE
Add support for Dominion: Renaissance

### ISSUE THREAD

**Issue by wvoigt** [sumpfork/dominiontabs#210]
Add support for Dominion: Renaissance

http://riograndegames.com/Game/1334-Dominion-Renaissance

**Comment by nickv2002** [comment]
😃 just saw this too. My storage case is going to bust. It’s got 300 cards so that probably means 29 new cards in the set.

**Comment by joeskeen** [comment]
I'll be happy to tackle this one, as I plan to get Renaissance as soon as I can get my hands on it.

**Comment by joeskeen** [comment]
Actually, it looks like details on the cards are already available: http://wiki.dominionstrategy.com/index.php/Renaissance

I'll get started on this right away, so we can have a release ready when this expansion ships.

**Comment by nickv2002** [comment]
@joeskeen Thanks for your offers to help. We tend to break up new sets into sub-tasks and work on various parts of those. Thanks to online info we don't need to wait until we get the physical copies either (the full card text and rules are usually released online before the physical cards ship out). All that will probably happen in late October.

Based on the [spoilers posted this week](http://wiki.dominionstrategy.com/index.php/Renaissance) it looks like we need to define new card types for **Project** and **Artifact**. We should also consider going back to Guilds and [rewording the coin tokens as Coffers](https://dominionstrategy.com/2018/09/26/renaissance-previews-3-villain-ducat-silk-merchant/).

**Comment by wvoigt** [comment]
I created Pull #215 to get things started.  I think I have most of the structural changes in place.
Still needed are the card text, actual images (instead of placeholders), and the CI tests.

**Comment by wvoigt** [comment]
I see that this release is supposed to happen near the end of the month.  If anyone sees other card information before then, please post here.  I think we have 11 unkown Kingdom cards, 2 unknown Atrifacts, and 14 unknown Projects to be added.

**Comment by nickv2002** [comment]
I won't have time to work on this anytime soon but the [full card spoiler](http://dominionstrategy.com/2018/11/05/dominion-renaissance-release-and-card-spoilers/) and [manual (PDF)](http://riograndegames.com/getFile.php?id=2122) are available now. 🎉

**Comment by wvoigt** [comment]
I hope to get to it this week or on the weekend.

**Comment by wvoigt** [comment]
I could use some help proof reading.  Here are some sample files.
https://github.com/sumpfork/dominiontabs/pull/215#issuecomment-437548834

**Comment by nickv2002** [comment]
Yes. 👏 Thanks @wvoigt! Great work & fast as always. 😄
Wish I could have helped more but I'm busy with my other GitHub boardgame aid 😉 (for [Imperial Assault skirmish maps](https://github.com/nickv2002/Imperial-Assault-Skirmish-Map-Project))

Is this the last expansion? I kind of hope so but have my doubts!
