### ISSUE TITLE
German text on Adentures

### ISSUE THREAD

**Issue by idlaviV** [sumpfork/dominiontabs#213]
If I want to create Adventure-tabs with german text, I get "Server Error (500)" and there is no pdf. Also, there is no preview of the set in the right column.

The issue seams to lie at the card-texts of Adventures itself, if I choose "blank" or "rules" for both sides, the file is generated without an error. I could not reproduce the error for other sets than Adventures.

**Comment by sumpfork** [comment]
Yes, the tags in other language need to be fixed - my mistake, as I didn't catch them all when I fixed them for English. There's also the issue that more card texts are used when grouping special cards, which is the default for the online generator.

I'll fix them and also add a test that catches this in the future.

**Comment by idlaviV** [comment]
I saw that you commited new code and it works now. However, there seems to be an analogous error when I include expansion dividers (in english or german).

**Comment by sumpfork** [comment]
I believe this is fixed in 3.5.1, which is now deployed. Please reopen if not.
