### ISSUE TITLE
Reword Guild Coin Tokens to Coffers

### ISSUE THREAD

**Issue by nickv2002** [sumpfork/dominiontabs#214]
Donald X says [the new wording is retroactive here](https://dominionstrategy.com/2018/09/26/renaissance-previews-3-villain-ducat-silk-merchant/).

**Comment by wvoigt** [comment]
As a first attempt in the Renaissance branch, I've changed all 
take a Coin token
to 
+1 Coffers (take a Coin token)
This way if someone has an older version or they don't know what Coffers are yet, it reads about the same.  But I'm open to other suggestions.

**Comment by nickv2002** [comment]
I think the parenthetical note is good. 👍

**Comment by wvoigt** [comment]
Closing since the bulk of this was done with Renaissance Pull #125.  What is left will be documented in issue #231
