### ISSUE TITLE
monochrome option for black and white printing

### ISSUE THREAD

**Issue by chad56s** [sumpfork/dominiontabs#225]
It would be nice to leave the color off, especially on the banners on the tab. I print on different colored paper to distinguish sets and the color doesn't translate very well sometimes.

**Comment by nickv2002** [comment]
Closing this as _won't do_

My suggested fix is to run the PDF you generate through your computer's print dialog and select Black & White there. Then you can print directly from there or export to a new PDF. (Both Mac and Windows should support this through their standard print dialogs.)
