### ISSUE TITLE
Minor typos

### ISSUE THREAD

**Issue by md5i** [sumpfork/dominiontabs#231]
Minor typo in the text for Improve: "acrd" -> "card".

**Comment by wvoigt** [comment]
Minor typo in the rules of Swamp Hag: "you will get..." -> "You will get..."

**Comment by wvoigt** [comment]
Butcher should be reworded (I missed this in the other updates for issue #214.
"Take two Coin tokens. " should be "+2 Coffers (take two Coin tokens).<br>"

**Comment by wvoigt** [comment]
I'm bunching these all up since it will take a run of /tools/update_language.py to fully incorporate these.  They can also be picked up the next time a language update is done.
