### ISSUE TITLE
Change to language processing

### ISSUE THREAD

**Issue by sumpfork** [sumpfork/dominiontabs#234]
I would like to change how we process language files to follow a more commonly used pattern.

Right now, we have the actual card database and all translations in the python package under `domdiv/card_db`. We also treat this as the source files for creating languages using `tools/update_language.py`, which rewrites the card database into `tools/card_db`, doing a bunch of work like interpreting the 'untranslated' tags. This version of the card database must then be copied manually to replace the `domdiv` one. We have tests to check that this has been done, and that there are no differences between the two databases.

I'd like to:
- have the source for `card_db` live at the top level of the repository, not in the `domdiv` package
- have `update_language.py` create `domdiv/card_db` from this top level source
- add a build tool like `doit` to do this and other tasks like tests and release in a unified, more easily documentable manner
- add an automatic deployment step that processes the card_db source into the package using said build tool
- change the tests so that they do not check that the build tool has been run (which will now happen automatically), but to check that there are no actual content changes that would affect the output (like bad `untranslated` entries that get replace translated content with the English version, rather than formatting changes of the JSON files) between the source and the destination.

That way it's clear what's the source for the card db, and what is the deployed version, and there's no extra manual step of replacing the source with the generated version.

Does this make sense, @wvoigt?

**Comment by sumpfork** [comment]
To note, I have a local branch in the works that does most of this, other than changing the tests to be more semantic.

**Comment by wvoigt** [comment]
@sumpfork I agree that it is a pain now.   It was why I was wanting to bunch up some of the text changes -- just to minimize this turn of the crank.
You may want to change the top level directory name so it is clear which directory contains the source and which contains the files that will be overwritten (but used.)
