### ISSUE TITLE
Urchin and Hermit Card Text

### ISSUE THREAD

**Issue by sfsholes** [sumpfork/dominiontabs#238]
Selecting "card text" will produce the "card rules" for both Urchin and Hermit (with Urchin on one side and Madman on the other or just Urchin if there is no back). Similarly, Knights produces a card rules -like text as opposed to the shorter and more descriptive Castles or traveler card text options. 

![urchin](https://user-images.githubusercontent.com/31464522/49695351-105c2180-fb57-11e8-8e7b-d2d64bb42a7c.PNG)

**Comment by wvoigt** [comment]
A view of the new card text:
[238-2.pdf](https://github.com/sumpfork/dominiontabs/files/4396099/238-2.pdf)
