### ISSUE TITLE
Option for Just Expansion Labels/Just Special Cards/Just Resources

### ISSUE THREAD

**Issue by Sunthief** [sumpfork/dominiontabs#240]
It would be nice to have an option to create a PDF with just the expansion labels, or just the resource/special cards (project etc.) labels in the form. You might need some a couple times.

**Comment by ranneyd** [comment]
I had this exact same request.

I didn't fork or push anything because I'm lazy, but I cloned it and added this at line 1385 after `cards = filter_sort_cards(cards, options)`. Worked like a charm

```
    new_cards = []
    for card in cards:
        if card.isEvent() or card.isExpansion() or card.isLandmark() or "base" in card.cardset_tags or card.isType("Project"):
            new_cards.append(card)
    cards = new_cards
```

**Comment by wvoigt** [comment]
Here is a generic proposal that I believe covers the above request and more.   Add two new options that limit/reduce the number of dividers to the matching type(s) given. This would happen after any other options are used to select expansions, group cards, etc. Basically this is done right before the cards are sorted before they are printed.

* `--only-type-any,` alias `--type-any`
keeps any dividers that have *any* of specified types

* `--only-type-all`, alias `--type-all`
keeps any dividers that match *all* of the specified types

For example:
`--only-type-any project expansion` would include in the output only expansion and project dividers
`--only-type-all duration attack` would include in the output only dividers that had both duration and attack types.
`--only-type-any landmark --only-type-all duration action` would include in the output any landmark dividers AND any dividers that had both duration and action.

The current list of types include:
Action, Artifact, Attack, Blank, Boon, Castle, Curse, Doom Duration, Event, Events, Expansion, Fate, Gathering, Heirloom, Hex, Landmark, Landmarks, Looter, Night, Prize, Prizes, Project, Reaction, Reserve, Ruins, Shelter, Shelters, Spirit, Start Deck, State, Trash, Traveller, Treasure, Victory, Zombie

Matches would be to these type names or their corresponding text in the language specified.  All case insensitive.  I have a prototype of this that I can post as a branch if this makes sense to everyone.

Comments?

**Comment by sumpfork** [comment]
Deployed
