### ISSUE TITLE
Avery 8867 alignment problem

### ISSUE THREAD

**Issue by sumpfork** [sumpfork/dominiontabs#245]
From BGG user `mhawk731`:

> I think your program has a bug with left aligned text on the 8867 Avery label size. Right align and center align works, but left align just does center align again.
> 
> The only options I have modified are:
> Page size -> Avery 8867
> Tab align -> left
> 
> I have uploaded a screenshot for you as well:
> https://imgur.com/a/AIHU33C

**Comment by wvoigt** [comment]
I believe this is now fixed.  Basically I missed a qualifier in an if statement.   The getClosestSide() == "centre" clause should only work if the tab name align was set to "edge".  

This covered the case where there are an odd number of tabs and the name align is set to "edge".  So tabs to the left have the tab names aligned to the left, and tabs to the right to aligned to the right. But tabs in the exact center have no "closest" edge, so they were made to be in the centre.

**Comment by sumpfork** [comment]
Deployed
