### ISSUE TITLE
Avery 8867 verticle/horizontal offset option

### ISSUE THREAD

**Issue by timur-tabi** [sumpfork/dominiontabs#248]
Could you add an option to provide a user-specified offset of the entire page, vertically and horizontally?  The labels align perfectly now, which is great, but unfortunately for me, my plastic dividers are a little too short, and so I want the labels printed slightly higher on the page (closer to the top edge of the labels).

I was able to make the adjustment I needed by slicing 1mm off the top of the label sheet, then printing the page upside down.  But it would be nice if I didn't have to do that.

**Comment by wvoigt** [comment]
This change is included in Pull #301
