### ISSUE TITLE
PDF Output Displays Borders On Every Other Page

### ISSUE THREAD

**Issue by blue-onyx** [sumpfork/dominiontabs#25]
Submitted form from web front end at:

http://sandflea.org/

using settings as indicated in "Form Settings.png"

Page 1 output was good as displayed in "Output Good Borders.png"
Page 2 output was missing borders as displayed in "Output No Borders.png"

See attachments...
Thanks for your amazing contributions!
Warm regards,
blue-onyx

OS X 10.8.5 viewing the generated PDFs in Mac Preview 6.0.1

![form settings](https://cloud.githubusercontent.com/assets/15018260/10344636/fcb09fc0-6ce9-11e5-9060-6c318fc47fd6.png)
![output good borders](https://cloud.githubusercontent.com/assets/15018260/10344644/05457bf6-6cea-11e5-8299-43761e2ac9f5.png)
![output no borders](https://cloud.githubusercontent.com/assets/15018260/10344650/0bd9a1d6-6cea-11e5-80a2-dcba3f4f4eea.png)

**Comment by sumpfork** [comment]
This is intentional for 2-sided printing on commodity printers: the borders rarely line up correctly on front and back and are just cutting aids, so they are never printed on the back pages.
