### ISSUE TITLE
Left-alignment not working in Tab Options

### ISSUE THREAD

**Issue by zenroch** [sumpfork/dominiontabs#250]
The issue presents in both horizontal and vertical tabs, using the online generator.

Initially noticed the issue with these tab options: 

Number of tabs: 1
Starting tab location: full width
Tab name align: left

**Comment by zenroch** [comment]
Likely related to issue #245.. used letter size paper when I saw the issue

**Comment by sumpfork** [comment]
ok, might just be that I haven't deployed this - will try to get to asap.

**Comment by zenroch** [comment]
Thank you, I can't wait! Your program is such a wonderful tool. I'll upload photos of my collection using them once I can print out new ones for Renaissance :)

**Comment by sumpfork** [comment]
Deployed

**Comment by zenroch** [comment]
Beautiful, thank you thank you
