### ISSUE TITLE
Make option for full width tab, centred label

### ISSUE THREAD

**Issue by sumpfork** [sumpfork/dominiontabs#26]
I've gotten this request several times: full with tab with a centred label for the dividers. Shouldn't be hard to add.

**Comment by wvoigt** [comment]
I thought I would take a stab at this.  And I thought it would be more versatile to have two options: 

* One for a full tab (--fulltab) that aliases --tabwidth with the correct value
*  one for centered names (--center_name) 

They can be used independently or together.

Changes in dominion_tabs.py:
About line 798 after

    parser = OptionParser()

 add:

    parser.add_option("--fulltab", action="store_true", dest="fulltab",
                          help="force all label tabs to be full width")
    parser.add_option("--center_name", action="store_true",
                          help="Center the card name on the tab")

about line 949 change:

        if self.options.orientation == "vertical":
            self.tabWidth, self.tabBaseHeight = dominionCardHeight, dominionCardWidth
        else:
            self.tabWidth, self.tabBaseHeight = dominionCardWidth, dominionCardHeight

        fixedMargins = False

to:

        if self.options.orientation == "vertical":
            self.tabWidth, self.tabBaseHeight = dominionCardHeight, dominionCardWidth
        else:
            self.tabWidth, self.tabBaseHeight = dominionCardWidth, dominionCardHeight

        if self.options.fulltab:
            self.options.tabwidth = self.tabWidth / cm
            print 'Using full tab size, %.2fcm' % (self.options.tabwidth)

        fixedMargins = False

about line 453 replace:

            if rightSide or not self.options.edge_align_name:
                w = textInset

with:

            if rightSide or not self.options.edge_align_name or self.options.center_name:
                if self.options.center_name:
                    w = self.tabLabelWidth / 2 - self.nameWidth(line, fontSize) / 2
                else:
                    w = textInset

I tested on several cases, but I don't have a full test suite.  So I hope I didn't break anything else.

**Comment by wvoigt** [comment]
If you give me permission, I will submit the code.

**Comment by sumpfork** [comment]
Hi,

Could you just issue a GitHub pull request?

Thanks,
Peter

**Comment by wvoigt** [comment]
It's telling me I don't have permission to do that.
- Wendel

**Comment by sumpfork** [comment]
Hmm, I get pull requests all the time from folks. I'm not at my computer at the moment, but did you follow something like 
https://yangsu.github.io/pull-request-tutorial/ ? What's the link to your branch on github?

I should have time to check into this later today.

Thanks,
Peter

**Comment by sumpfork** [comment]
I can see your branch at https://github.com/wvoigt/dominiontabs <https://github.com/wvoigt/dominiontabs> but you don’t seem to have pushed anything to it. Once you push your changes there you should be able to issue a pull request against my branch from yours.

Peter

**Comment by sumpfork** [comment]
This is now all live on the generator thanks to @wvoigt.
