### ISSUE TITLE
Dominion Menagerie Expansion Support

### ISSUE THREAD

**Issue by nickv2002** [sumpfork/dominiontabs#273]
Here we go again. [Donald X says](https://www.reddit.com/r/dominion/comments/dg7lfd/errata_to_the_errata/f3ebqyq/):
> There will be an expansion next year, probably first quarter.

On one hand I'm excited but on another hand my current box with fancy dominiontabs dividers can **not** hold any more cards. 🙃

**Comment by sumpfork** [comment]
Ha

**Comment by nickv2002** [comment]
[Expansion announced](https://boardgamegeek.com/boardgameexpansion/298055/dominion-menagerie):

> Dominion, that's what you're trying to achieve. This time with animals! They each have a lesson to teach, whether it's how to spit really far or what kind of grass tastes the best. It's a lot to keep track of, but you're like an elephant: you remember everything. And you're afraid of mice. You've taken up riding. Horses are intimidating; they say you can lead a horse to water, but you haven't managed it, so you're working your way up, starting with dogs. So far so good; the dog hasn't bucked you off yet. Your menagerie got off to a poor start, with just a goat, two rats, and the advisor who suggested starting a menagerie. You couldn't get that fox you wanted, but it was probably bad anyway. Now you've got some camels, which are just as useless for sewing as you'd been warned, and a turtle that can hold its breath for longer than anyone can stay interested. Soon the animal kingdom will be yours.
> 
> **Dominion: Menagerie**, the 13th expansion to Dominion, has 400 cards, with thirty new Kingdom cards. There are Horses that save a draw for later, Exile mats that cards can be sent to and rescued from, and Ways that give Actions another option. Events return. You need the basic cards and rulebook in order to play Dominion: Menagerie, which can be combined with any other expansion in the game series.

**Comment by nickv2002** [comment]
The [full Menagerie set set is available from the Dominion wiki](http://wiki.dominionstrategy.com/index.php/Menagerie_(expansion)
[Also rulebook PDF](http://riograndegames.com/getFile.php?id=2220)

**Comment by nickv2002** [comment]
Not sure I'll find time to work on this soon given everything that's going on, but I'll poke at it when I do have time. Thanks and stay healthy everyone.

**Comment by wvoigt** [comment]
I can start working on this.
