### ISSUE TITLE
Update Cards with the 2019 Errata rules

### ISSUE THREAD

**Issue by TheZoc** [sumpfork/dominiontabs#275]
Hello,

Recently, DonaldX published an errata for the current dominion cards:
https://boardgamegeek.com/thread/2281518/dominion-2019-errata-and-rules-tweaks

These are the cards that needs updating:
- Band of Misfits
- Overlord
- Inheritance
- Lantern
- Death Cart
- Pillage
- Embargo
- Procession

With appropriate instructions (how to deal with the errata / how to have both instructions on the separator (old and new one)), I can update the cards and send a pull request.

Thanks for the awesome tabs! :)

**Comment by nickv2002** [comment]
I also intended to do some errata updates from this 2nd edition a few years ago (see  https://github.com/sumpfork/dominiontabs/issues/136) but never got around to it.

IMO, all the errata version can just overwrite the old text. I don't see a reason to keep the old versions around. They can be looked up online if needed but people should be playing with the newer and clearer wordings anyway. But I'd be curious to see if other people have different ideas.

**Comment by sumpfork** [comment]
I agree, let's replace, as 'errata' implies.

**Comment by TheZoc** [comment]
I created #276 with most of the changes. I could use some help with the extra text, so it's worded correctly :)

Thanks! 😁

**Comment by TMDaines** [comment]
Any chance we can get a filter to just print dividers for cards that were errataed in 2019?

**Comment by nickv2002** [comment]
2019 & 2020 errata changes incorporated into in https://github.com/sumpfork/dominiontabs/pull/346
