### ISSUE TITLE
Dot-cropmarks on back side are in wrong place

### ISSUE THREAD

**Issue by DarthGandalf** [sumpfork/dominiontabs#284]
[sumpfork_dominion_tabs (3).pdf](https://github.com/sumpfork/dominiontabs/files/4002911/sumpfork_dominion_tabs.3.pdf)

Looks like for the back side, the offset is calculated from the opposite direction (right vs left)

**Comment by wvoigt** [comment]
Alexey,
Can you be more specific on the issue.  From the PDF, it looks correct to
me.   The Dots seem to be in the correct place.  The dashes only only on
the edges to show a dot is in that line.
- Wendel

**Comment by DarthGandalf** [comment]
On the front side, the dots are in correct place.

**Comment by wvoigt** [comment]
fixed in Pull #301
