### ISSUE TITLE
Missing Prize Cards when "Group Special Cards (e.g. Prizes)" checked

### ISSUE THREAD

**Issue by noacess** [sumpfork/dominiontabs#293]
Hi,

When trying to generate a set for just Cornucopia if I check the "Group Special Cards (e.g. Prizes)" option the special cards are not included in the PDF.  If I omit this option they're included.

**Comment by wvoigt** [comment]
They are included.  They are included with the "TOURNAMENT AND PRIZES" tab.  One way to see this is to enable the "Show number of Cards per Divider" under Body options.  When selected you see that there are 10 cards and 5x1 cards (so a total of 15) for that divider.
