### ISSUE TITLE
Title in multiple languages

### ISSUE THREAD

**Issue by Gnomiro** [sumpfork/dominiontabs#294]
Would it be possible to allow multiple languages for selection? E.g. choosing a main-language for card-text and rules and an additional language for showing two card titles at the top like: "Cellar (Keller)"

This would be especially useful when looking for card sets created by an english only app (while playing in german) or when having cards from in different languages.

I assume this change would be relatively simple and I could potentially pull the git and add the chages by my self?

**Comment by sumpfork** [comment]
Not sure it's actually that simple - most of the code intentionally does not reason about which language things are being produced in, so switching language in the middle of rendering is going to require some work. If it's really just two and in not too many places you could perhaps load the secondary language and have it ready during render time.

**Comment by Gnomiro** [comment]
Thanks! Found the corresponding part and currently trying to realise it in a nice way so I that I maybe can create a merge request.

As of looking into the code it seems so that " / " was initially designed to mark the preferred position for splitting card names if they are to long but it is never removed or even used (see draw.py line 1272 "if tooLong"). Am I right? 

For multple language titles a good way of splitting is essential and the "/" character would be a good option but than has to be removed if no split is necessary. This seems to be a missing thing currently.
