### ISSUE TITLE
Expansion dividers with full tab width

### ISSUE THREAD

**Issue by Gnomiro** [sumpfork/dominiontabs#295]
Is it possible to make expansions dividers to have full width while having alternating not-full width tabs for other cards?

As fas as I searched in the code it seems that the tabWidth parameter is global and used for all cards, isn't it? It seems only to be possible to center make the expansion dividers centered with "--centre-expansion-dividers".

**Comment by wvoigt** [comment]
Added this function in pull #301 
Added option `--full-expansion-dividers` that makes expansion dividers full width with centered text.
