### ISSUE TITLE
One card tab at the wrong position when using "--tab-number 2 --tab-side right-alternate"

### ISSUE THREAD

**Issue by Gnomiro** [sumpfork/dominiontabs#296]
I tested this on my local computer as well as on the website. If you generate the tabs with "--tab-number 2 --tab-side right-alternate" or in my case more specific:

dominion_dividers --papersize A4 --orientation vertical --back blank --front rules --count --tab-name-align edge --set-icon body-top --tab-artwork-opacity 0.8 --special-card-groups --expansion-dividers --centre-expansion-dividers --expansion-reset-tabs --exclude-events --exclude-landmarks --tabwidth 5 --tab-number 2 --tab-side right-alternate

The first card after the "Base" seperator is centered but only this one. If you use "--tab-side left-alternate" this is not the case. Maybe it is related to some modifications which are made for the Base-Card generation. Potentially the "tabOffsetBack" is not set back to 0?

In addition why are base cards not alternating their position? Is there any special reason for this?

**Comment by wvoigt** [comment]
Fixed in pull #301
