### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by sumpfork** [sumpfork/dominiontabs#30]
Checking the actual pdf output would be quite a bit of work, so for now
- check that the various flags execute ok
- check that the input files are valid JSON of the expected format
- add these tests for github to run

**Comment by sumpfork** [comment]
The framework is there now, and the tests run on github. More tests should be added.

**Comment by wvoigt** [comment]
So instead of checking the PDF, can we leave some form of bread crums for each card that says what was used to print it.  For example, what divider front side text option was used.  Same for back side.  For that card's tab, what side was it on (left, right, full),  how was that card's front tab text aligned.  How was it's back side tab text aligned.  Etc.

This would be stored on a card by card basis.  Then we could set the options, and at the end query a card to two to make sure all the tab flipping, alignment changes, etc are correct.
I'm thinking something generically of the form:

def record4test(self, card, test-attribute, value)

and then some way of getting / testing that pairing during the tests.

It still means we trust the output to PDF, but this would check to make sure a lot of the basic logic is correct.

**Comment by sumpfork** [comment]
I have to think some more about that - is it actually beneficial to do anything per-card? For now, I think making tests to make sure that

1) all options actually run in all legal combinations
2) the options at least change the thing they're supposed to change

would already go a long way. I was thinking about auto-generating all possible option combinations, but maybe that would be too slow.

**Comment by wvoigt** [comment]
Yes, your (1) and (2) would seem to offer the basic testing.  I completely understand if you don't want to go deeper.   

This is long winded, but just in case, I wanted to put my thoughts down...
My reasoning on the per card was even greater coverage.  
On any given sheet of paper, cards differ from other cards or have particular attributes from the options.  For example:
* front tab location - left, right, full (especially if they are alternating)
* front tab text alignment - left, right, center, (edge is either a true left or right for a given card)
* front body text - blank, card text, extra rules text
* back tab location - left, right, full (should be opposite of front side if left/right)
* back tab text alignment - left, right, center (should be opposite of front side)
* back body text
* icon location - tab, body, hide, text
* cost location - tab, body, hide

Now in the code, if we set these per card attributes in the code segments right when things are done, then we know that that code segment was exectued for that card.

For example for the cost:
First initialize somewhere:

        record4test(card, 'cost', 'hide')

 in `drawTab`, when the cost is to be put on the tab:

        # draw cost
        if not card.isExpansion() and not card.isBlank():
            if 'tab' in self.options.cost:
                record4test(card, 'cost', 'tab')
                textInset = 4
                textInset += self.drawCost(card, textInset, textHeight,
                                           card.getType().getTabCostHeightOffset())

and then in `drawText`, when the cost might be put on the body

        if 'body-top' in self.options.cost and not card.isExpansion():
            record4test(card, 'cost', 'body')
            self.drawCost(card, cm / 4.0, totalHeight - 0.5 * cm)
            drewTopIcon = True

Now we have a way to actually check to make sure that not only the `--cost` option was set, but we have a way to verify that the correct code segment was actually executed to do what is expected for that setting.  And in a small way, it also helps document the code segments.  This is not as good as a visual check of the PDF, but if we place the collection points in the right spots, we have a very good indication that things will output as expected.

For any given test of options, we probably would only need to generate 2 pages (enough for front back).  Maybe limit to one expansion.  Then by checking the front/back attributes of two cards, it is possible to make sure all the right left/right/back flip/tabs/text alignments, etc happened as expected for those options.

Now it may make sence to have a special test mode.  That way `record4test` (or what ever it is called) could be smart and only record things when we are testing.  And the test mode could be used to prevent the actual writing of PDF files.

Anyway, just my thoughts.

**Comment by sumpfork** [comment]
I was mainly trying to set priorities, to get the basic testing done first.

And I understand your sentiment, but I'm hesitant about the requirement to explicitly add calls into the code for testing - the calls can be wrong or out of date with respect to the code, and the tests would be rendered meaningless.

If we're going to go this far, here's what I think we should do instead: create a test-only version of reportlab's canvas class and implement the calls on it that we use, but just keep track of how things are being moved and placed. That way we can write tests that check that a certain image is in a certain place on a certain page, etc., without modifying the actual generation code. It'd be a good chunk of work, but I think it'd be a better test of the functionality. What do you think?

**Comment by sumpfork** [comment]
Alternatively, the canvas class already has a `getCurrentPageContent()` method - we could read back the pdf generated that way and check that things are in the right places. For example, `BT 1 0 0 1 278.082 28.34646 Tm /F2+0 12 Tf 14.4 TL (Adventures) Tj T* ET` in there shows the matrix used to place 'Adventures' on the page. If we're writing tests for drawing only a few things this may be feasible.

**Comment by sumpfork** [comment]
Looking for libraries to help, let's use pdfminer. Simple skeleton:
```python
from pdfminer.converter import PDFLayoutAnalyzer
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.pdfpage import PDFPage
import sys
from pdfminer.layout import LTChar, LTFigure


class PDFChecker(PDFLayoutAnalyzer):
    def __init__(self, rsrcmgr):
        PDFLayoutAnalyzer.__init__(self, rsrcmgr)

    def receive_layout(self, ltpage):
        print 'page: {}'.format(ltpage)
        chars = []
        for item in ltpage:
            if isinstance(item, LTChar):
                chars.append(item)
            else:
                if chars:
                    print ''.join(c.get_text() for c in chars)
                    chars = []
                if isinstance(item, LTFigure):
                    print '  figure: {}'.format(item)
                    for fitem in item:
                        print '    figure item: {}'.format(fitem)
                else:
                    print item

analyzer = PDFChecker(PDFResourceManager())
fp = file(sys.argv[1], 'rb')
interpreter = PDFPageInterpreter(PDFResourceManager(), analyzer)
for page in PDFPage.get_pages(fp, pagenos={1}, check_extractable=True):
    interpreter.process_page(page)
```
