### ISSUE TITLE
One sided version with rules

### ISSUE THREAD

**Issue by sumpfork** [sumpfork/dominiontabs#31]
From BGG user InfoCynic:
```
Is it possible to generate:
* 1-sided
* Omit card text
* Include rules text 

That way if we're printing on one-sided labels or taping a lightweight paper to something heavier, we
have the important info (the rules text). We can always read the cards if we want to know what they
say.```

**Comment by sumpfork** [comment]
Note that we almost have this: --no-card-backs already prints only the fronts, but there currently isn't a way to print the rules instead of the card texts, just a way to leave out the rules.

**Comment by wvoigt** [comment]
I was thinking of generalizing this a bit more. While it may be a little overkill, to let folks do whatever they want, I'm thinking of two options:
`--front`, options are 'card-text', 'extra-rules', 'blank'; default = 'card-text'
`--back`, options are 'card-text', 'extra-rules', 'blank', 'none'; default = 'extra-rules'
 The cases are:

Divider Front | Divider Back | Comment
------- | ------ | ------------
Card Text |  Extra Rules |  the default
Card Text | Card Text | symetric, no front/back, can flip divider
Card Text | blank | could be used to keep divider simple? Not sure how useful.
Extra Rules| Card Text |  reverse of default, solves #31 with --no-card-backs
Extra Rules    | Extra Rules | symetric, no front/back, can flip divider
Extra Rules        | blank | solves #31 with --no-card-backs
blank  | Card Text   | not interesting, flip of above option
blank | Extra Rules| not interesting, flip of above option
blank | blank | same as --no-card-rules
Card Text | none | single sided with Card Text
Extra Rules| none | single sided with Rules, solves #31
blank | none | single sided with no text



`--no-card-rules` then sets these to both 'blank'.
`--back none` is the same as `--no-card-backs`.  I figured this would be easier to implement in a pull-down.  But this could also be removed and just have the `--no-card-backs`.

While I know this could be done with a couple more true/false flags, I'm thinking that this would then be easier to implement in two pull-downs on the webpage (and will be easier for someone to understand.)  Even if it means they have a few uninteresting options.

What do you think?

**Comment by sumpfork** [comment]
Sure, I'm fine with consolidating the options this way. I say we get rid of '--no-card-rules' then - there are already too many flags.

Also note that I added a unit test framework, so if you have the time you could add some checks that these are being interpreted correctly as you go along.

**Comment by sumpfork** [comment]
reopening until deployed.
