### ISSUE TITLE
'Group Special Cards (e.g. Prizes)' does not work

### ISSUE THREAD

**Issue by markschlosser** [sumpfork/dominiontabs#320]
On the sandflea.org page, the 'Group Special Cards (e.g. Prizes)' toggle does not work.

I tried the option with Cornucopia and all the individual prizes each have separate dividers.

Also, the dual piles in Empires have separate tabs for each of the two cards in the pile.  Previously, I was able to have dual piles for Empires - Catapult / Rocks under a single divider before.  Now I get separate dividers - "Catapult" and then "Rocks" each have their own dividers.

**Comment by sumpfork** [comment]
I deployed https://github.com/sumpfork/bgtools_web/pull/18 - can you check that it's now working as expected?

**Comment by sumpfork** [comment]
Resolved via sumpfork/bgtools_web#18
