### ISSUE TITLE
Exclude non-supply cards

### ISSUE THREAD

**Issue by DavidGasku** [sumpfork/dominiontabs#321]
Hi, great project, I'm currently putting all my sets together. I've a suggestion.
I'd like to store non-supply cards that are related to some card (like travellers), with their supply card, as you always want to get them together.
I could not use them, and put all related travellers together, but it breaks the divider pattern (left-right). So it would be very helpful to have an option to remove those cards from the layout.
Thanks!

**Comment by markschlosser** [comment]
Is this somewhat related to #320?

**Comment by DavidGasku** [comment]
Seems so. I checked that option, and as travellers had their dividers, I assumed they weren't a group. Thanks.
