### ISSUE TITLE
The River's Gift.

### ISSUE THREAD

**Issue by gstephan30** [sumpfork/dominiontabs#335]
Just as a question, is there a particular reason, why "The River's Gift." has a dot at the end? Its consistent in all languages and bases. I was just wondering. All other cards incl gifts don't end with a dot.
Thank you for your great work.

**Comment by nickv2002** [comment]
Pretty sure it's just a typo.

**Comment by nickv2002** [comment]
Closed with release https://github.com/sumpfork/dominiontabs/releases/tag/v3.13.0
