### ISSUE TITLE
Update cards with the 2020 errata

### ISSUE THREAD

**Issue by TMDaines** [sumpfork/dominiontabs#344]
A number of cards from Seaside, Prosperity and Hinterlands received further errata in October 2020. Some of this was functional and some was more cosmetic. I see the 2019 errata still has not been merged though.

http://forum.dominionstrategy.com/index.php?topic=20551.0

One thing I would love to do is to be able to reprint specific dividers just for those cards that have received errata.

**Comment by nickv2002** [comment]
2019 & 2020 errata changes incorporated into in https://github.com/sumpfork/dominiontabs/pull/346
