### ISSUE TITLE
Request: Ability to exclude specific cards

### ISSUE THREAD

**Issue by kompressor2279** [sumpfork/dominiontabs#347]
I'd like the ability to omit certain cards from generating tabs.

This came about when I was creating tabs for my set with alternating tabs.  I have a few expansions, but not Alchemy, and I also have a few promos but not all of them. 

The issue is, if you choose your tabs to alternate from left to right. What do you do with the tabs for the cards you don't have? (The Potion is part of the 'base' set) Either leave them in the box, or remove them. Neither is a great option.  It would be best to have a way to exclude the missing cards so the tabs are not generated in the first place and not messing up the alternating tabs. 

Thanks!

**Comment by sumpfork** [comment]
Note that you should be able to work around this by using the `--cardlist` option which filters the cards added down to those with names listed in the given file. Not convenient, but workable.

**Comment by bszonye** [comment]
This would also help me organize dividers for Nocturne. I store my Heirlooms with the starting decks, so I don't need dividers for them. Configuring that has an additional problem. If I use `--group-special` then the Heirlooms get attached to their associated kingdom, but if I turn it off, then the boons, hexes, and states all get individual dividers instead of a single card for each group. Either way, I get some unwanted dividers or the wrong wrapper size.

**Comment by bszonye** [comment]
I'm running into a problem even when using `--cardlist`: If I turn on `--group-special` to group sets like `Boons` and `Page → Champion` then I cannot even select the parts of card groups separately. For example, with `--group-special` turned on, I cannot select `Pooka` and `Cursed Gold` separately, only `Pooka / Cursed Gold` or nothing. I will probably need to keep two separate card lists, one for grouped cards and one for ungrouped cards.

**Comment by wvoigt** [comment]
See Pull #400
Lines in the file specified by --cardlist can now either include a card or exclude a card.
Include works as before. Optionally, you can now add a '+' at the start of a line.
To exclude a card, just preface the line with a '-' (minus).
There can be white space before and spaces/tabs after the + or -
