### ISSUE TITLE
Dominion: Allies

### ISSUE THREAD

**Issue by nickv2002** [sumpfork/dominiontabs#352]
Well, here we go again:

> Dominion: Allies, the 14th expansion in the Dominion series, contains 400 cards, with 31 new Kingdom card piles that contain allies who will do favors for you and split piles that you can rotate.

It's apparently set for a December 2021 release. Here's the [BGG Page](https://boardgamegeek.com/boardgameexpansion/347307/dominion-allies), and the [Dominion Wiki Page](http://wiki.dominionstrategy.com/index.php/Allies).

![](https://cf.geekdo-images.com/ciPd3-T7ejgAY4gWzsxUqQ__imagepagezoom/img/qAPCy7ZIRXmx1GxbsXvp7S_t_pE=/fit-in/1200x900/filters:no_upscale():strip_icc()/pic6399550.jpg)

**Comment by AlessandroFasse** [comment]
I would offer my help for this. When the German version is released (February 2022) I can add the German and English versions of the cards.

**Comment by nickv2002** [comment]
Now estimated for a March 2022 release [according to this](https://boardgamegeek.com/thread/2759111/article/39337284#39337284).

**Comment by nickv2002** [comment]
Rulebook: https://www.riograndegames.com/wp-content/uploads/2021/09/Dominion-Allies-Rules.pdf
Card List: http://wiki.dominionstrategy.com/index.php/Allies

**Comment by cunday** [comment]
I can add the Dutch translations :)

**Comment by Slbx5245** [comment]
Hey Everybody, does anyone know when the Allies file will be added to the generator? Love these and really hope to update my storage system.

**Comment by sumpfork** [comment]
> Hey Everybody, does anyone know when the Allies file will be added to the generator? Love these and really hope to update my storage system.

#376 adds the expansion and cards, but no card text yet.

**Comment by Slbx5245** [comment]
Thanks!

**Comment by sumpfork** [comment]
#377 and #376 are now in the default branch, providing the card list and the main text for Allies - no descriptions for the back of the dividers yet.

**Comment by mkol** [comment]
Small problem: each Ally has "empires" at its set :(

**Comment by sumpfork** [comment]
> Small problem: each Ally has "empires" at its set :(

I fixed that and also added a quick temporary background for their tabs.

**Comment by mkol** [comment]
Few more Allies typos:

IS:

0: "Architects Guild"
1: "City-State"
2: "Crafters Guild"
3: "Forest Dweller"
4: "Trappers Lodge"
5: "Woodworkers Guild"

SHOULD BE

0: "Architects' Guild"
1: "City-state"
2: "Crafters' Guild"
3: "Forest Dwellers"
4: "Trappers' Lodge"
5: "Woodworkers' Guild"

(and old typo "GateKeeper" => "Gatekeeper" :) )

**Comment by md5i** [comment]
I am in the process of adding the FAQ ("extra") information to the Allies cards.  I'm about halfway finished.  I'm posting here in the hopes of not accidentally duplicating effort.

**Comment by Slbx5245** [comment]
Outstanding!

Steve Baetz 
CH (LTC) USA Retired

**Comment by md5i** [comment]
Initial version as pull request #381.

**Comment by sumpfork** [comment]
I've put Allies as its supported so far on the online generator. Thanks all for helping out so much! I'll close this issue for now and we can open new ones as we find any problems.

**Comment by Slbx5245** [comment]
Hi Everybody,

Does anyone know why I can't generate a full set of dividers? Everytime I
try, it times out. I can do smaller sets but not everything. Was able to
generate everything before Allies was added. Thanks
Steve

**Comment by sumpfork** [comment]
I seem to be able to generate the full set no problem, though it does take a while. Maybe it's your browser timing out? What browser/platform/version are you on?


> Hi Everybody, Does anyone know why I can't generate a full set of dividers? Everytime I try, it times out. I can do smaller sets but not everything. Was able to generate everything before Allies was added. Thanks Steve

**Comment by Slbx5245** [comment]
Safari but I also tried Chrome.

Steve
