### ISSUE TITLE
request: option to select 2nd edition + removed cards

### ISSUE THREAD

**Issue by bszonye** [sumpfork/dominiontabs#359]
I have a full set of 1st and 2nd edition cards for the base game and Intrigue, and I keep all of the redundant cards in deep storage. Therefore, my main collection contains all of the 2nd edition cards and the 12 cards that were removed in the upgrade. I would like a way to select just those 12 cards without bringing in all of dominion1stEdition and intrigue1stEdition. Perhaps introduce two new sets similar to the 2ndEditionUpgrade sets, but reversed?

dominion1stEditionRemoved = Adventurer, Chancellor, Feast, Spy, Thief, Woodcutter
intrigue1stEditionRemoved = Coppersmith, Great Hall, Saboteur, Scout, Secret Chamber, Tribute

**Comment by bszonye** [comment]
I see that I can use `--cardlist` to print just those 12 cards on their own, which is helpful. It would still be nice if I could select them directly with `--expansion` though, to include them easily in larger lists without getting two copies of all the cards that carried over to 2nd edition. If there's another good workaround, that would be fine too.

**Comment by bszonye** [comment]
Even with `--cardlist`, I'm having a hard time selecting *only* the 2nd edition cards along with the removed cards. If I set `edition = all` then I get two versions of the cards that appear in both editions, but if I set `edition = latest` the script filters out *all* of the 1st edition cards, including the removed cards that I want to keep.

**Comment by wvoigt** [comment]
Isn't the 2nd edition plus the removed cards the same as the 1st edition plus the upgrade (new) cards?

`--expansion dominion1stEdition --upgrade-with-expansion`
instead of
`--expansion dominion2ndEdition`
My understanding is that for the dividers, the card texts are the same for both additions (the latest with errata).  The only difference are the cards contained in each set.  The only difference I can think of right now is that the set icon for the common cards will be 1st edition instead of 2nd addition.

**Comment by bszonye** [comment]
Thanks for the feedback! Unfortunately, it doesn't help because I don't want the upgrades and removed cards sorted together. I keep the "removed" 1st edition cards separately, along with the promo cards. So far, the best method I've found for this is to print the 1st edition cards in a separate batch, with a `--cardlist` to select only the 12 cards. Every other approach that I've tried either produces two copies of the common cards or sorts them with the 1st edition cards (which affects tab positions).

(Also, this relies on the bug reported in #383, implicitly adding sets via `--upgrade-with-expansion`. That's easy enough to fix by adding `*upgrade*` to the expansions list. I'm linking the two issues so that fixes to one issue don't make the other one worse.)

**Comment by wvoigt** [comment]
Anyone have an objection to adding these sets:

- dominion1stEditionRemoved = Adventurer, Chancellor, Feast, Spy, Thief, Woodcutter
- intrigue1stEditionRemoved = Coppersmith, Great Hall, Saboteur, Scout, Secret Chamber, Tribute

This would make things somewhat consistent.  Between any two editions, each card will be in two sets and fall into one of these 3 groups:

- 1st Edition and 2nd Edition (covers the majority of cards)
- 1st Edition and 1st Edition Removed (new)
- 2nd Edition and 2nd Edition Upgrade (covers the upgrade packs)

Will this clutter up the expansion selection list too much?  With all the upcoming 2nd editions in queue, we will have a lot of these in the expansion selection list.

**Comment by nickv2002** [comment]
Sounds good to me @wvoigt 
The new and removed seaside cards are all known at this point. [See the Dominion wiki](http://wiki.dominionstrategy.com/index.php/Seaside#Removed_first-edition_Kingdom_cards)
