### ISSUE TITLE
crop marks missing from partial pages

### ISSUE THREAD

**Issue by bszonye** [sumpfork/dominiontabs#361]
On the last page of a job, crop marks do not appear after the rightmost column unless there is:

* at least one full row on the page, or
* a horizontal gap between cards larger than the crop mark length

Likewise, crop marks do not appear below the bottom row unless every row is used, or there's a vertical gap between cards. This appears to be the consequence of this code in `draw.py`:

                    pageItems[i].cropOnTop = (y == rows - 1) or RoomForCropV
                    pageItems[i].cropOnBottom = (y == 0) or RoomForCropV
                    pageItems[i].cropOnLeft = (x == 0) or RoomForCropH
                    pageItems[i].cropOnRight = (x == columns - 1) or RoomForCropH

That only crops on the outside rows, which might be empty on the last page of a job.

**Comment by wvoigt** [comment]
I am unable to test this out at the moment, but I think the following may do what you want:
```
                last_item = len(pageItems) - 1
                last_row = (rows - 1) - (last_item  // columns)
                pageItems[i].cropOnTop = (y == rows - 1) or RoomForCropV
                pageItems[i].cropOnBottom = (y == last_row) or (y == last_row + 1  and x > last_item % columns ) or RoomForCropV # bottom row, or next to bottom to the right of the last item
                pageItems[i].cropOnLeft = (x == 0) or RoomForCropH 
                pageItems[i].cropOnRight = (x == columns - 1) or (i == last_item ) or RoomForCropH # end of column or the last item
```

**Comment by bszonye** [comment]
Thanks! That code looks reasonable to me. It's similar to how I would have solved the problem. I'll help out with testing, and if I get to it first I'll send a PR.
