### ISSUE TITLE
Seaside Second Edition

### ISSUE THREAD

**Issue by nickv2002** [sumpfork/dominiontabs#364]
Looks like we're getting a [second edition of Seaside](https://boardgamegeek.com/blogpost/127727/dominion-seaside-see-second-edition-april-2022) with new cards for us to add:

> In April 2022, RGG expects to release Dominion: Seaside (Second Edition), with this expansion for either of the Dominion standalone titles containing nine new types of Kingdom cards; as happened with the new cards for the previous second editions, these cards will be released on their own as an update pack for those who own the first edition of Dominion: Seaside. A few cards will receive minor errata, but these will not appear in the update pack.

![Seaside Second Edition Box Art](https://cf.geekdo-images.com/b1Wt16vN_Skln_Hlz6S-EQ__imagepage/img/vfWGp6YjSDICAkW2AQCg7Okryu4=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6654841.jpg)

**Comment by nickv2002** [comment]
[Previews incoming](https://boardgamegeek.com/thread/2867341/preview-1)
There will be an [upgrade pack again](https://www.riograndegames.com/games/dominion-seaside-2nd-edition-update-pack/) so we can add cards to that also

**Comment by nickv2002** [comment]
The new and removed Seaside cards are all known at this point. [See the Dominion wiki](http://wiki.dominionstrategy.com/index.php/Seaside#Kingdom_cards.2C_second_edition)

**Comment by wvoigt** [comment]
From Pull #394, I've added a PDF of the resulting Seaside sets.  I can use some more eyes on it.
The one thing I **did not** do is double check existing cards for any text updates or errata.
[test7.pdf](https://github.com/sumpfork/dominiontabs/files/8774793/test7.pdf)
