### ISSUE TITLE
grouping and card count incorrect for Allies

### ISSUE THREAD

**Issue by mr-ice** [sumpfork/dominiontabs#386]
When using --wrapper and --expansions=Allies I get most of the  Kingdom card wrappers out ok.

However, some of the new kingdom cards and special cards are different size sets.  For example the Augurs which have 16 cards.

When printing the wrappers, I expect these to be 1.6 times as thick as the regular wrapper.  They are closer to 3 (could be 3.2).

There are seven card sets where the wrappers are significantly oversized... 
Allies
Augurs
Clashes
Forts
Odysseys
Townsfolk
Wizards

The outstanding one is Allies, which is not one of the new 16 card sets but should be pretty normal special (not kingdom card) set.

Full options I use:
```
bin/dominion_dividers \
--minmargin=1.25x1.25 \
--no-page-footer \
--notch-length=1.30 \
--order=expansion \
--orientation=vertical \
--papersize=letter \
--size=sleeved \
--sleeved \
--special-card-groups \
--tab-side=right \
--tabwidth=4.75 \
--thickness=2.57 \
--wrapper \
--expansions="$@"
```

**Comment by wvoigt** [comment]
You have --special-card-groups set. In the Clashes grouping there are 32 cards. You can confirm this by printing with  --count
I suspect it is similar for others.

**Comment by mr-ice** [comment]
update: the Allies wrapper is the correct size (24 cards fit well)

16 augurs is larger than the Allies wrapper

Here are the Allies, Augurs, and Carpenter side-by-side

<img width="964" alt="Screen Shot 2022-05-05 at 9 34 08 PM" src="https://user-images.githubusercontent.com/1105176/167057438-3d434404-50fb-4687-9e7f-d43c8f183f2d.png">

**Comment by mr-ice** [comment]
> You have --special-card-groups set. In the Clashes grouping there are 32 cards. You can confirm this by printing with --count
> I suspect it is similar for others.

Correct, without it the Allies don't generate a wrapper

Printing with --count, I do not see Clashes and other 4x4 sets showing 32 cards:

<img width="963" alt="Screen Shot 2022-05-05 at 9 44 58 PM" src="https://user-images.githubusercontent.com/1105176/167058698-d7bf5572-df43-4b85-98de-6e6fadd83222.png">

**Comment by mr-ice** [comment]
however, turning off --special-card-groups does work for Clashes and Augurs, but --count in both cases shows 16:



<img width="961" alt="Screen Shot 2022-05-05 at 9 51 56 PM" src="https://user-images.githubusercontent.com/1105176/167059134-ae28268a-5aba-44a3-afeb-1c7f5bb917e4.png">


This at least provides me with a workaround to reprint these few

**Comment by wvoigt** [comment]
I'm not sure what is the problem.  When I generate with --special-card-groups set, I see Clashes (the grouping of cards) with card counts of [16] 4x[4] which is 16 cards and 4 sets of 4 cards, which is 32 cards in total.  Same for Augurs, Forts, Odysseys, Townsfolk, and Wizards.
The Clashes grouping contains Clashes (16), Archer(4), Battle Plan(4), Territory(4) and Warlord(4).
Is this not an expected grouping of cards?  I'm just going by how the card database is set up.  I don't have the expansion yet to compare against.

**Comment by mr-ice** [comment]
Ahh, I see now what you are saying... No, clashes is 16 cards, not 16 and then additional 4x4

The clashes are just four copies of the four named cards.

**Comment by wvoigt** [comment]
OK, I'm finally getting to the rule book.  I think we are on the same page.  This has exposed a couple of issues:
1. For Augurs, Clashes, Forts, Odysseys, Townsfolk, and Wizards, the card db is coded incorrectly.  There should NOT be a card db entry with the grouping name (and card count).  There should be a (and is) a text entry for the grouping card. For example, this should not be in the db, is not needed, and is causing problems:
```   
   {
        "card_tag": "Clashes",
        "cardset_tags": [
            "allies"
        ],
        "cost": "3*",
        "count": "16", 
        "group_tag": "Clashes",
        "group_top": true,
        "types": [
            "Action",
            "Clash"
        ]
    },
```
This causes the group to always print, and it incorrectly then adds the member cards to this entry when --special-card-groups is set.

1a, I would also add that the Group Card text should include the individual card listing & summaries as well.
1b. I'm not sure why the group tag is "Clashes" with a capital C, when elsewhere the convention has been to use lower case.

2. Since Ally cards are horizontal non-cards, I think they should be treated like Events, Landmarks, etc.

I think this issue needs to be renamed.

**Comment by mr-ice** [comment]
I have attempted to rename the issue -- Please feel free to correct it if it is still inadequate.

> Since Ally cards are horizontal non-cards, I think they should be treated like Events, Landmarks, etc.

Yes, exactly

**Comment by mr-ice** [comment]
Also note that I submitted [PR#385](https://github.com/sumpfork/dominiontabs/pull/385) for the spelling of Allies (Alies) in your quote from the db.

**Comment by wvoigt** [comment]
Upon further review and testing, Augurs, Clashes, Forts, Odysseys, Townsfolk, and Wizards are different.  Each has a randomizer, but no cards with the same name.  Hence, the card db entry needs to stay so it prints and is in the randomizer list.  But the count is zero.  When `--special-card-groups` is selected, then the 4 groups of 4 cards are placed onto this "Group".  When `--special-card-groups` is NOT selected, the 4 groups of 4 cards are printed themselves, and the Clashes card is also printed (but has no cards in it). Presumably, one could then put those cards behind this divider.

```
   {
        "card_tag": "Clashes",
        "cardset_tags": [
            "allies"
        ],
        "cost": "3*",
        "count": "0",   <==== change from 16
        "group_tag": "Clashes",
        "group_top": true,
        "types": [
            "Action",
            "Clash"
        ]
    },
```
I am almost ready for the pull request.
