### ISSUE TITLE
--write-json option doesn't do anything

### ISSUE THREAD

**Issue by md5i** [sumpfork/dominiontabs#388]
The `--write-json` options doesn't seem to be hooked up to any code.

**Comment by wvoigt** [comment]
Any reason not to just remove?  I'm not sure what the intention was.

**Comment by md5i** [comment]
No, I suppose not.  I found out when I was attempting to generate a list of card names so I knew the exact text needed for entries for the `--cardlist` option.  I ended up hacking the code to generate the list.  It might be nice to have an option to do this.

**Comment by sumpfork** [comment]
This is from when I move from yaml to json format to avoid the external library dependency. Can be removed.
