### ISSUE TITLE
Expose option for "Special Card Groups" on web page

### ISSUE THREAD

**Issue by davidjrawlings** [sumpfork/dominiontabs#39]
Could you add a tick-box on the web-page for the "--special_card_groups" option.  Thanks.

**Comment by stormybriggs** [comment]
I would love this option. This flag is the whole reason I downloaded the code. I don't want a tab for each prize, traveller, etc.

**Comment by sumpfork** [comment]
This is done, as of today. There's an option (selected by default) in the right hand list of the generator page now.
