### ISSUE TITLE
Server error when trying to make dividers for Extras

### ISSUE THREAD

**Issue by jcoplin** [sumpfork/dominiontabs#395]
When I try to create the dividers for "extras," the server errors out with "Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

If I try and generate a preview, it simply spins.

**Comment by sumpfork** [comment]
Extras isn't something you can select on its own, because they're extras from other sets.

I agree this is totally unclear from the interface and shouldn't just error in this obscure way.

**Comment by sumpfork** [comment]
I changed this in the online generator. There is no 'Extras' entry anymore, but rather it gets added transparently if you select to generate global groups for some events.
