### ISSUE TITLE
Cannot generate Heirlooms Divider from Nocturne

### ISSUE THREAD

**Issue by jopalenc** [sumpfork/dominiontabs#401]
I have tried every combination of grouping options and cannot figure out how to generate a divider for "Heirlooms."

I have searched open issues and Google:

Your search - site:https://boardgamegeek.com/thread/926575/ heirlooms - did not match any documents.

And have not seen this problem reported elsewhere.

**Comment by wvoigt** [comment]
If no `--group-special` is specified heirlooms print individually. If `--group-special` is specified they are grouped with their corresponding kingdom card. Heirlooms are not "landscape" cards like events, landmarks, ways, etc. There is no option to print them as a group.
