### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by Propmask** [sumpfork/dominiontabs#405]
Hi

I was using the site https://domdiv.bgtools.net all day yesterday to print some Dominion Dividers, but all of a sudden I can't access the site anymore.  I get an error message about not being able to locate the server. I see some expansions were updated yesterday also, could this be the cause for the server failing?

**Comment by nickv2002** [comment]
@sumpfork Does the server need a good kick?

**Comment by sumpfork** [comment]
Sorry, routing problem after I switched it to also have a staging version. Should be back up.
