### ISSUE TITLE
Rules Text verbage

### ISSUE THREAD

**Issue by CodeMastr3** [sumpfork/dominiontabs#406]
I've been looking through the rules text and I would like to suggest a change to 4 instances.
At least 4 cards Duke, Harem, Great Hall, and Nobles say "During set-up, place 12 *card name here* in
the Supply for a 3- or 4- [or 5- or 6-] player game and 8 in
the Supply for a 2-player game."
While Mill says "Use 8 Mills for games with 2 players, 12 for games with 3
or more players."
I feel like the Mill example is much more concise and should be adopted for the other 4.

**Comment by sumpfork** [comment]
We've usually gone with the official rules text from the rulebooks if it exists, and I'm hesitant to diverge.

**Comment by CodeMastr3** [comment]
I have the Dominion Intrigue rulebook here in front of me and it goes with the style of Mill, not whatever the other style is.

**Comment by CodeMastr3** [comment]
![20220814_212132](https://user-images.githubusercontent.com/18755358/184576615-21a3c96e-feed-4ca2-86a8-6e662c6605d8.jpg)
![20220814_212118](https://user-images.githubusercontent.com/18755358/184576620-1599b296-12f5-40f2-914b-6363359502eb.jpg)

**Comment by sumpfork** [comment]
Seems to be an edition difference - I can find pdfs of the first edition with different Duke wording online. Haven't dug out my own rulebook, but likely the same old wording that's also still on dominion strategy. I'm fine to change it then.
