### ISSUE TITLE
Show previews of different options

### ISSUE THREAD

**Issue by Jargonius** [sumpfork/dominiontabs#41]
If there were picture previews of each option then we wouldn't have to generate an entire pdf just to see what one small change does.

**Comment by sumpfork** [comment]
I did some work on a live preview that just renders the first page (or part of it) to an updating picture on the site as you change options. Need to find time to get back to that - the code to render the preview is there, but the site needs instrumentation to trigger the updating.

**Comment by sumpfork** [comment]
This is live on the generator now - first page gets previewed as a png whenever an option changes. Obviously, it's not possible to see many order or back page changes and options like that this way.
