### ISSUE TITLE
German translation for Seaside2nd edition and other small things

### ISSUE THREAD

**Issue by Xedorian** [sumpfork/dominiontabs#410]
Hey,
I wanted to provide the German translation of Seaside 2nd edition, rule texts for some promo cards and update the German names of two cards but sadly don't have the necessary writing access. I did create a fork but couldn't get any further. Help would be appreciated with that. Thanks

**Comment by sumpfork** [comment]
Hi, thanks for helping out! You would need to [create a Pull Request from your fork to the repo](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by Xedorian** [comment]
So I'm seemingly running into some problems but have no idea how I'm supposed to interpret their details (see my pull request). Sorry for the hassle. I would love to help but seemingly can't.

**Comment by sumpfork** [comment]
The test is telling you that your JSON format is not valid: `card_db_src/de/cards_de.json: Failed to json decode (Expecting ',' delimiter: line 2868 column 1 (char 451824))`. I recommend producing the files locally (see https://github.com/sumpfork/dominiontabs#translations) so you can verify that things work as expected.

**Comment by sumpfork** [comment]
This is deployed now, thanks!
