### ISSUE TITLE
Dominion: Plunder Expansion

### ISSUE THREAD

**Issue by nickv2002** [sumpfork/dominiontabs#420]
Well no end in site for new Dominion cards. RGG just announced **Dominion: Plunder** ([BGG](https://boardgamegeek.com/boardgameexpansion/369536/dominion-plunder))

> Across the sea, they have so much stuff. And it's so much better than your stuff. Finer craftsmanship. Better quality materials. Shinier. They have crowns, tiaras, and diadems — and that's just the hats. It's time to get some of that stuff. You want an easy life, and you're prepared to work hard for it, so you've rounded up some old salty dogs, plus a sourpuss and a bitter goldfish. And set sail. The sea is a harsh mistress, but a good cook, at least if you like everything really salty. There are red skies tonight, so they'll be making a batch of Sailor's Delight, which you understand to have tuna fish in it. And soon you'll be attacking merchant ships and taking their treasure. But the real treasure is the happy memories you'll be making.
> 
> Dominion: Plunder, the fifteenth expansion for Dominion has lots of Treasures and Durations, with cards that give you Loot, and Traits that modify piles. Events return.

Release TBD, presumably by the end of 2022.
![pic7035290](https://user-images.githubusercontent.com/704392/187744407-5a2696c4-e1d9-4cec-a619-bc98b5a5ffa6.jpg)

**Comment by nickv2002** [comment]
The [official rulebook](https://www.riograndegames.com/wp-content/uploads/2022/08/DomPlunder.pdf) and [Dominion Strategy wiki Page](http://wiki.dominionstrategy.com/index.php/Plunder_(expansion)) (with text of all cards) are up now.

**Comment by databoy01** [comment]
Is it done yet…lol. Look forward to this expansion!

**Comment by md5i** [comment]
Well, I got my physical copy yesterday.

**Comment by md5i** [comment]
So, I am working on this.  I'm writing some scripts to scrape the raw data from the Dominion Strategy Wiki.  I need a reminder, though.  Am I supposed to be editing the files in `card_db_src` or the files in `src/domdiv/card_db`?

**Comment by md5i** [comment]
Also, is there a noticeable difference between `<n>` and `<br>` in output?  Under what circumstances should one be used versus the other?

**Comment by sumpfork** [comment]
> So, I am working on this. I'm writing some scripts to scrape the raw data from the Dominion Strategy Wiki. I need a reminder, though. Am I supposed to be editing the files in `card_db_src` or the files in `src/domdiv/card_db`?

`card_db_src` is the right spot, and the `doit update_languages` to generate the in-package copy. I'm tempted to compress the in-package copy just do this confusion doesn't keep occurring...

**Comment by sumpfork** [comment]
> Also, is there a noticeable difference between `<n>` and `<br>` in output? Under what circumstances should one be used versus the other?

I haven't actually checked recently, but `<br>` is at least mentioned as an official line break tag in the reportlab docs, so go with that?

**Comment by sumpfork** [comment]
> > So, I am working on this. I'm writing some scripts to scrape the raw data from the Dominion Strategy Wiki. I need a reminder, though. Am I supposed to be editing the files in `card_db_src` or the files in `src/domdiv/card_db`?
> 
> `card_db_src` is the right spot, and the `doit update_languages` to generate the in-package copy. I'm tempted to compress the in-package copy just so this confusion doesn't keep occurring...

I did this: https://github.com/sumpfork/dominiontabs/pull/427

**Comment by md5i** [comment]
A few more questions:

With Loot, I have added an entry for each type of Loot in the `cards_en_us.json` file.  I have also added a **Loot** entry.  Based on Ruins, I guess I should ass a **Loot** entry to the `cards_db.json` file, but not add the individual cards themselves, and to add the "Not currently used" comment on the `cards_en_us.json` file?

I am assuming that Traits should be handled the same way as Events and Ways are handled?

**Comment by md5i** [comment]
What is the purpose of the `types_db.json` file?  Should I be adding an entry with every unique type combo that does not already exist?  Should I add an entry for "Loot" by itself with a `defaultCardCount` of `2`?  Not certain how to properly modify this right now.

**Comment by md5i** [comment]
As a followup to last, For **Way** you have **Way** and **Ways** in the `types_db.json`.  What is the reason for each?  Should I be doing the same for **trait** and **Traits**?

**Comment by md5i** [comment]
Looks like we need a `trait.png` banner.  I'm not really skilled at photoshopping, so I intend to copy `way.png` for now and let someone else handle that bit.

**Comment by md5i** [comment]
Initial pull request up as #430.

**Comment by sumpfork** [comment]
Just starting to get to this, haven't looked at the PR yet, but to answer some questions:

- the types db exists for a couple of purposes: to allow for translating card types separate from the cards themselves, and to do some listing/linking of card types, for example for global groups
- speaking of global groups, the reason that `Way` and `Ways` both exist is the `--group-global` option that collects special card types across all expansions and prints a, for example, `WAYS - ALL` divider for Ways. I'm not sure I like the naming of this option and how exactly it works (it completely ignore expansion selection at the moment), but there's much cleanup to do in other places, too.
- as to what exactly to do with Loot, we'll have to decide. For some the generator always produces a card divider (e.g. `Ruins`) but also defines a card type so it can have a special tab image etc.. For some (e.g. `Events`) there is a divider for each card specified in the card db, but it has both a `group_tag` (e.g. `adventures events`) and the `Event` type also has the `Events` global group type. This means that without additional options you'll get a divider per event, with `--group-special` you'll get a divider per expansion (e.g. `EVENTS - ADVENTURES`) and with `--group-global` you'll get a single divider for all expansions, e.g. `EVENTS - ALL`. I suspect the latter setup is what we want for `Loot`.
- yes, a standing image if perfectly fine for now.

**Comment by md5i** [comment]
FWIW, I ended up putting all the Loot cards in the English DB, but chose not to have them in the cards_db, and instead have a single Loot card there instead.  This is analogous to, say, Castles.  The individual card entries aren't used, but they are there for future expansion and library purposes.

**Comment by sumpfork** [comment]
Merged, released and in the online generator. Future bugs can get their own issues raised. Thanks!

**Comment by databoy01** [comment]
Looks great. THANK YOU!
