### ISSUE TITLE
Script usage documentation is not up-to-date in the github wiki

### ISSUE THREAD

**Issue by md5i** [sumpfork/dominiontabs#431]
It would be nice if CI would be able to update that automatically.  I don't know if that is possible, but it might be worth looking into.

**Comment by sumpfork** [comment]
CI actually runs it,  it because of permissions I can't update PRs from others forks, so all it does is create its own PR if running the db creation creates changes.

**Comment by sumpfork** [comment]
Sorry, I think I misunderstood your issue. I thought you're talking about running the script compiling the db, but you're talking about updating the help replicated in the wiki? I can look into that, yeah.

**Comment by md5i** [comment]
Yes, that is what I meant.
