### ISSUE TITLE
Trouble installing Minion fonts

### ISSUE THREAD

**Issue by md5i** [sumpfork/dominiontabs#438]
According to the `README.md` files in both the base and `src/domdiv/fonts` directories, I'm supposed to put the `ttf` files in the `src/domdiv/fonts` directory and run `setup.py install`.  But this does not copy the fonts into the `egg` file.

I feel like I'm probably doing something wrong.  Hints/pointers?

**Comment by sumpfork** [comment]
I think you either 1) need to use a development install (i.e. `python setup.py develop` or `pip install -e .`) or 2) remove [this line](https://github.com/sumpfork/dominiontabs/blob/master/MANIFEST.in#L5). We could probably make the latter the default now that packages are always built in CI which won't have the font files anyway, it was just meant for me to not forget to remove them when building package locally before.

**Comment by md5i** [comment]
Ah, understood.  Thank you.  It might be nice for the documentation to clarify that point.

**Comment by sumpfork** [comment]
Yes, I need to go over all the docs honestly.
