### ISSUE TITLE
Group Special Cards (Shelters) are incorrect color

### ISSUE THREAD

**Issue by Bob-A-Mickelson** [sumpfork/dominiontabs#45]
When Shelters are grouped the banner label is white and red. the banner label should be solely red as not all shelters are not Action-Shelters. (White-Red) The color all shelters have in common is red. This is also how Dark Ages lists Shelters in the box insert. 

BTW great job on putting together this program.

**Comment by wvoigt** [comment]
I'm in the process of making changes for #47 and #48 and while I'm there I can work on this.
