### ISSUE TITLE
Request for Placeholder Randomizer Tab

### ISSUE THREAD

**Issue by Bob-A-Mickelson** [sumpfork/dominiontabs#46]
**Could we get a Placeholder/Randomizer tab?** I would think a blue banner would suffice.

On a similar note it seems odd to me with Empires coming out that there Events (and I presume Landmarks) have set icons on their banner. Events are no longer expansion specific. Also its a bit distracting/odd looking since the icon covers part of the banner pattern which kinda blurs both the pattern and icon together in an not so readable way. Same goes for the coin icons on events.   Would it be possible to include an option to print Events, Landmarks, Randomizers without set Icons/Coins at the end of the PDF as well so we wouldn't have to print off 3 extra pages for each of these since they will likely be scattered throughout the document.

**Comment by nickv2002** [comment]
Since there's only 1x of each Event and not that many in total. I'm fine storing them all under a single Event section.  Are other people planning to split them between two Adventures Events and Empires Events sections?

**Comment by Bob-A-Mickelson** [comment]
I plan to have all events under a single tab irregardless of expansion (adventures, promo, empires etc.). Same goes for landmarks (empires, the announced promo etc.) likewise I keep my randomizers under a single tab as well. Though I understand why some choose to segregate those.

**Comment by wvoigt** [comment]
The option to have events and landmarks as a separate group across all expansions is available in the generator code.  It just needs to be brought out to the web interface. See help for `--exclude_events` and `--exclude_landmarks`.

**Comment by sumpfork** [comment]
Closing this for now as the `exclude` options mentioned above are now exposed - can make a new issue if there's other needs.
