### ISSUE TITLE
Add Card counts to database, have option to print on dividers

### ISSUE THREAD

**Issue by wvoigt** [sumpfork/dominiontabs#47]
I want the option to print the number of cards on the divider, with the following extras:
1. For groupings, if only the one divider is printed, then that displays the sum of all the cards under that grouping.
2. The same goes for Events and Prizes

**Comment by wvoigt** [comment]
I did want to have a discussion on the best (or should I say acceptable) way to add the card counts.  There are a couple of options:
1. The obvious one is to add a
`  "count": xx, `
in every entry in the cards.json.  This would be a lot of work and it must be done for each and every language as well.
2. Noticing that most card types have a consistent number of cards, this could be a quicker way to add the counts across all languages.  However, there are about 10 cards that are exceptions to this.

I'm proposing a hybrid.  Implement (2).  Then for the 10 or so exceptions, add those to the cards.json.  Many fewer mandatory changes to cards.json.  In effect, if a "count" is in the cards.json it is used, otherwise use the default for the card type specified.

This approach also has the bonus of making a transition to (1) easier if that is ever wanted.

Does this sound reasonable?

**Comment by sumpfork** [comment]
Hybrid sounds good to me.
