### ISSUE TITLE
Option to print dividers as wrappers or slipcases

### ISSUE THREAD

**Issue by wvoigt** [sumpfork/dominiontabs#48]
I would like to have the option to print the dividers as wrappers / slipcases.  Similar to [hgzwopjp's Dominion slipcases](https://boardgamegeek.com/filepage/64912/hgzwopjps-dominion-slipcases-horizontal-vertical-c).  He has not updated them for the last expansion and has not replied to messages.

To make the wrappers / slipcases, one must know the thickness of the stack of cards.  So this is dependent on #47.

**Comment by sumpfork** [comment]
Note that I have a complete solution for generating card tuckboxes in python that I'd be willing to open source for this if it helps.

**Comment by wvoigt** [comment]
Thanks.  I'm just about done.  My last task is to go through the other language files to fix them up.  I have two comments/questions:

1. Updating the language files is not easy.  It looks like some are missing cards.  I would think there should be a better way to do this.  There is a lot of redundant structure data.  Maybe a primary file, and then the other languages just provide the text changes for that language.  The nice part of that would be that once a card is added to the base language, the card will show up, just not in the other language.  Possibly prompting others to help fix/add. I would think that would take some form of key for each card.  Can't be the name since some are used across sets, but possibly set-name.  I would think that would be unique.
2. The changes for the card count and wrapper/slipcase are pretty extensive.  Did you want them just submitted, or would you prefer them in a separate branch until more eyes can take a look at it?

**Comment by wvoigt** [comment]
You can see the changes now at:
https://github.com/sumpfork/dominiontabs/compare/master...wvoigt:master

**Comment by sumpfork** [comment]
Looks pretty good on first glance. Want to submit a pull request, or should I test it off of your branch first?

**Comment by wvoigt** [comment]
I made a few minor updates to clean it up a little.  I would feel more comfortable if it was tested a little more.  I've run through a number of tests, but a second set of eyes is always good.   It *should* behave the same for all previous options.

**Comment by wvoigt** [comment]
Also note this addresses issues #47 and #45

**Comment by sumpfork** [comment]
Honestly, just make a pull request, otherwise I'll keep forgetting it's in the pipeline and to test it :).
