### ISSUE TITLE
Dominion Empires Rulebook is out. 

### ISSUE THREAD

**Issue by Bob-A-Mickelson** [sumpfork/dominiontabs#49]
Need to add dominion Empires kingdoms and also landmarks,
http://riograndegames.com/Game/1306-Dominion-Empires

**Comment by nickv2002** [comment]
Kind of hard to see the actual cards in the rules.  Let's hope we get some higher resolution version of the cards and someone does some work transcribing the actual words on the card first.

**Comment by sumpfork** [comment]
The card text in the pdf is text I believe, it just takes a lot of reformatting.

**Comment by nickv2002** [comment]
Oh yeah, it is there in the card thumbnails if you zoom in.  Looked too small to read zoomed out.  Again, I'm going to hope someone transcribes this in the next few days.  If you find a link let me know.  Then I can do the text-editing work (which I'm pretty good at) to fix all the formatting.

**Comment by sumpfork** [comment]
Might be too much work to reformat, but here are html, json and txt extracts of the pdf. I won't have time to look at them for a bit.

[Empires.txt](https://github.com/sumpfork/dominiontabs/files/304078/Empires.txt)
https://www.dropbox.com/s/qyzjqo3wq3chpic/Empires.json?dl=0
https://www.dropbox.com/s/f8alppsma6i9v5d/Empires.html?dl=0

**Comment by nickv2002** [comment]
Looks like we've got a good start on a pull request with Empires content from @splatteredbits here: https://github.com/sumpfork/dominiontabs/pull/51

Hope I get some more free time to contribute soon.

**Comment by sumpfork** [comment]
I just merged https://github.com/sumpfork/dominiontabs/pull/52 which I believe finishes the bulk of Empires work, thanks to @bog. I'll close this issue and will update the online generator, further (hopefully minor) Empires problems can go into new issues.

**Comment by bog** [comment]
Thanks. I'm happy to take a look if anyone finds issues. I just printed my generated copy and everything worked great.
