### ISSUE TITLE
Custom card dimensions

### ISSUE THREAD

**Issue by I-Would-Like-To-Report-A-Bug-Please** [sumpfork/dominiontabs#495]
It'd be an amazing feature if we could specify custom card dimensions e.g. width x height.

**Comment by sumpfork** [comment]
This is already possible in the script. Web interface custom exposure is unlikely, but I'm thinking about ways to expose all script options in a (far more complicated) online interface.

**Comment by I-Would-Like-To-Report-A-Bug-Please** [comment]
Ah awesome! Gonna poke around tomorrow! Many thanks, closing then!
