### ISSUE TITLE
Way to print specific cards

### ISSUE THREAD

**Issue by thale13** [sumpfork/dominiontabs#496]
Is there a way to print select cards from different expansions? 

For example, I need Ambassador, Artificer, Menagerie (the card), Loot, Ruins, and Copper for some reason.  I don't want to print all of Seaside, Dark Ages, Hinterlands, Plunder, and Base.  (Its doubly wasteful if you print labels because the sheets become useless at that point).

Maybe a "fan expansion" could be added that asks for a CSV file that contains the list of cards to print?

if this is way off the reservation, feel free to close it and I'll figure out something for what I need.

**Comment by sumpfork** [comment]
Yes, use the `--cardlist` option. See https://github.com/sumpfork/dominiontabs/wiki/Documentation-%28Script-Options%29.

**Comment by thale13** [comment]
Thank you for the speedy response.  I hadn't gotten to using a local copy yet since the webpage does everything else that I need.

This is a great tool and I really appreciate it being available.
