### ISSUE TITLE
Missing NL-DU for Plunder

### ISSUE THREAD

**Issue by Greattigre** [sumpfork/dominiontabs#497]

**Comment by sumpfork** [comment]
Thanks for the note, but there are lots of translations missing for various languages and various expansions. We should maybe auto-compile a list of what's present and not, but I don't think we need an individual issue for each missing language/expansion pair.

**Comment by Greattigre** [comment]
I can help to translate this part

**Comment by sumpfork** [comment]
That's be awesome. Instructions to start, compile the card DB are here: https://github.com/sumpfork/dominiontabs?tab=readme-ov-file#translations. You'll end up making a pull request here that I can review.
