### ISSUE TITLE
Rising Sun, Marchland, 2nd Edition Cornucopia & Guilds

### ISSUE THREAD

**Issue by nickv2002** [sumpfork/dominiontabs#498]
FYI and future TODOs that new cards are incoming in the next few months.

- A new promo [Marchland](https://wiki.dominionstrategy.com/index.php/Marchland)
- A new expansion [Rising Sun](https://wiki.dominionstrategy.com/index.php/Rising_Sun)
	- Donald X says "My best guess is March 2024, but as usual I will know more in say February." 
- A 2nd edition for the [combined Cornucopia & Guilds expansion](https://wiki.dominionstrategy.com/index.php/Cornucopia_%26_Guilds)

**Comment by nickv2002** [comment]
Looks like we're getting a 2nd edition of Cornucopia & Guilds in march and the cards have already been revealed:
https://wiki.dominionstrategy.com/index.php/Cornucopia_%26_Guilds

I'll update the title of this issue to reflect that.

**Comment by thale13** [comment]
Any updates on this?  Just wondering.  Willing to help if you can point me in the right direction.

**Comment by nickv2002** [comment]
@thale13 I imagine we'll fold the promo and Corn/Guild 2nd Ed. updates into a Rising Sun update once those cards are known (that's how it's worked in the past). Not sure when that will be but probably soon. [Watch the Dominion Wiki for more info on that](https://wiki.dominionstrategy.com/index.php/Rising_Sun).

If you do want to get started you can add cards to the JSON card DB, eg Marshland would get a new entry [somewhere around here](https://github.com/sumpfork/dominiontabs/blob/master/card_db_src/cards_db.json#L7290-L7299).

**Comment by dbgalur** [comment]
This second edition / upgrade combines the Guilds and Cornucopia sets into a single set.  So we can talk about cards that were removed from the 1st edition of each, but the new cards are added to a combined set, rather than to a second edition of each individual set.  How would you represent the upgrade set in sets_db.json?  Specifically, "upgrades" expects a string rather than an array, no?

**Comment by dbgalur** [comment]
Actually, that may not be a relevant question.  5 of the new cards are clearly part of Cornucopia, while the other 3 new cards are part of Guilds, even if they are not explicitly marked with different icons.

**Comment by nickv2002** [comment]
We obviously try to match what has been physically printed because they're dividers for physical cards. So we'll have an upgrade set and a second edition set and a first edition set (see previous upgrade packs here). The upgrades and second edition will be for the dual pack, but the first edition remains separate.

**Comment by dbgalur** [comment]
Okay, so I've made what I think are the necessary changes to card_db_src/cards_db.json, card_db_src/sets_db.json, card_db_src/types_db.json, card_db_src/xx/cards_xx.json, and card_db_src/xx/sets_xx.json.

But I have close to 0 experience doing stuff with git / github, and have not succeeded in running the tests on Windows, so would love any assistance someone feels like they can offer.  (I suppose in the worst case I can just share the changes with someone and let them do the merge/commit/pull whatever the terminology is).

**Comment by dbgalur** [comment]
I've successfully managed to build/test the additions.  Now all that remains is to figure out how to commit the changes and propose a change...tomorrow.

**Comment by nickv2002** [comment]
Thanks for your work! If you want to learn Git and GitHub there are lots of tutorial videos on YouTube (I don't have any specific recommendations). I also think the [GitHub Desktop app](https://desktop.github.com) is a good tool for both beginners and pros so I'd recommend starting with that.

You're also welcome to zip up the json files and upload them to this thread if learning Git wasn't on your weekend list. 😆

**Comment by dbgalur** [comment]
I _think_ I've created a pull request?

I worked with git maybe about a decade ago, but never with GitHub..

**Comment by nickv2002** [comment]
Thanks @dbgalur

Now I just hope that Rising Sun is revealed soon!

**Comment by sumpfork** [comment]
Cornucopia and Guilds 2nd edition is packaged and deployed, thanks!

**Comment by md5i** [comment]
My attempt at adding Marchland is here: https://github.com/sumpfork/dominiontabs/pull/524

**Comment by nickv2002** [comment]
[All Rising Sun cards have now been revealed](https://wiki.dominionstrategy.com/index.php/Rising_Sun). I'm traveling at the moment so no help for adding them but figured I'd note it as I saw the news!

**Comment by tphinney** [comment]
Rising Sun is now shipping in physical form as well. (My copy is due to arrive on September 18.)

**Comment by parkerc92** [comment]
Any updates on plans to add Rising Sun? I just purchased a physical copy from my local game store, can't wait to set up the tabs!

**Comment by TistoH** [comment]
I've gotten mine.  I have added json for the all of the cards, card types (Omen, Prophecy, Shadow), and the set, including the en_us files.  I am missing the "extra" from the rulebooks (for the cards and card types), plus some more checking.  

I added "Rising Sun" to the bonuses.  I used "Rs" for the text set symbol.  I made crappy versions of prophecy.png and risinsun_set.png, and the latter may be broken for transparency?

My cygwin installation is not liking my attempts to update/install locally so that I can test (or use!) everything.

Unless somebody is further along, I can keep plugging away on "extra" text.

**Comment by sumpfork** [comment]
> I've gotten mine. I have added json for the all of the cards, card types (Omen, Prophecy, Shadow), and the set, including the en_us files. I am missing the "extra" from the rulebooks (for the cards and card types), plus some more checking.
> 
> I added "Rising Sun" to the bonuses. I used "Rs" for the text set symbol. I made crappy versions of prophecy.png and risinsun_set.png, and the latter may be broken for transparency?
> 
> My cygwin installation is not liking my attempts to update/install locally so that I can test (or use!) everything.
> 
> Unless somebody is further along, I can keep plugging away on "extra" text.

Great, thanks. I suggest making a PR sooner rather than later with your work in progress so we can have a look, make fixes, etc. Can land it without the extras, too, and just add the extras later.

**Comment by TistoH** [comment]
Unfortunately, the problem with installing locally is even keeping me from committing (because of the commit hook) on my own machine.  I have a patch file (made with "git diff --binary" so that the -- probably useless -- stand-in png files show up).
[Tisto_RisingSun.patch.gz](https://github.com/user-attachments/files/17106047/Tisto_RisingSun.patch.gz)

**Comment by sumpfork** [comment]
https://github.com/sumpfork/dominiontabs/pull/535 - please start working from that branch to avoid conflicts.

**Comment by sumpfork** [comment]
This is deployed to the online generator.
