### ISSUE TITLE
Cornucopia/Guilds 2e set icon

### ISSUE THREAD

**Issue by jctran** [sumpfork/dominiontabs#520]
The new second-edition cards for Cornucopia and guilds still use the old set icons - would it be possible to get this updated so that they use the new one? Thanks!

**Comment by nickv2002** [comment]
Quoting from https://github.com/sumpfork/dominiontabs/pull/517#issuecomment-2094875422

> We usually use [icons from here](https://boardgamegeek.com/filepage/73273/dominion-card-icons-vector-images) but that doesn't have a Corn/Guilds 2nd Ed update yet either. I'm watching the thread on BGG so I can add when they do have an update.

**Comment by ftckayes** [comment]
Found one here:
https://wiki.dominionstrategy.com/index.php/Category:Card_symbols

Not sure if it'll work/help, but it's there.
