### ISSUE TITLE
Guilds 2e Upgrade Pack

### ISSUE THREAD

**Issue by ftckayes** [sumpfork/dominiontabs#528]
I hate to be "that" guy - but it looks like the 2e icon for the Guilds 2e Update Pack didn't get changed with the latest update.

**Comment by ftckayes** [comment]
Me again... It looks like the Guild 2e Update Pack still isn't using the correct set icon. Sorry... =/

**Comment by sumpfork** [comment]
Where are you seeing that? The script has been updated, but I haven't done a web deploy. Are you using the script?

**Comment by ftckayes** [comment]
My bad - I saw the issue was closed and assumed that meant it was fixed.

I was just looking at the tabs I generated.

**Comment by sumpfork** [comment]
This is deployed now.
