### ISSUE TITLE
Add A3 papersize

### ISSUE THREAD

**Issue by finex** [sumpfork/dominiontabs#53]
Hi, would be possible to add "A3" paper size with no page margin? This would allow to print 16 dividers on each page. Thanks :-)

**Comment by wvoigt** [comment]
The code for this already exists using the stand alone program.  The options are:
`--papersize A3 --minmargin 0x0`

When I run it, I get:
- horizontal dividers: 6 rows of 3 cards
- vertical dividers: 4 rows of 5 cards (it just fits, almost going to the edge)

The work is making this available on the website.  The biggest part would be allowing minimum margins to be given as input.  An interim step might be adding an A3 option on the page size pull down.

**Comment by finex** [comment]
Adding the option to the website would be awesome! :+1:

**Comment by sumpfork** [comment]
Deployed.
