### ISSUE TITLE
A few typos in English databases

### ISSUE THREAD

**Issue by TistoH** [sumpfork/dominiontabs#532]
I have found typos in Citadel, Townsfolk, and Hermit.  I have a patch file, if someone would like to apply it.

**Comment by nickv2002** [comment]
Please attach the patch file here with instructions for applying or better yet [submit a PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)

Thanks for your help!

**Comment by TistoH** [comment]
Greetings,
Attached is a gzip-ed patch file from git diff against master branch.  Let me know if that isn't enough information.  
Thanks for your offer to help.  I'm not up to figuring out pull requests, repository forking, and the like just now.  Maybe if I get more involved.


 - Ron


    On Monday, September 16, 2024 at 07:46:43 PM MST, Nick Vance ***@***.***> wrote:  
 
 


Please attach the patch file here with instructions for applying or better yet submit a PR

Thanks for your help!

**Comment by TistoH** [comment]
[typos.patch.gz](https://github.com/user-attachments/files/17038095/typos.patch.gz)

**Comment by sumpfork** [comment]
Landed in #533, thanks!
