### ISSUE TITLE
Landmarks Banner Art Missing

### ISSUE THREAD

**Issue by ObtusePunubiris** [sumpfork/dominiontabs#56]
Unlike all other dividers, the tab for the Landmarks divider has no banner art.  Was expecting something similar to the Events banner, but green.

**Comment by nickv2002** [comment]
I used my menial image editing skills to put a test image together.
![landmark_nc](https://cloud.githubusercontent.com/assets/704392/16055764/6575b484-3227-11e6-9d35-2664bb9397e7.png)

**Comment by sumpfork** [comment]
Could you submit a pull request with that added? Thanks.
