### ISSUE TITLE
Add Action/Treasure banner image

### ISSUE THREAD

**Issue by sumpfork** [sumpfork/dominiontabs#60]
The Empire expansions has cards of this type that have a mixed banner image. We are currently using a simple Treasure banner instead. Easiest would be to scan the image from the box insert and add it in the same place as the others - code change is minimal.

**Comment by nickv2002** [comment]
High res scan is here: http://wiki.dominionstrategy.com/images/9/91/Crown.jpg
I'll try to do some image editing to get a version of it that we can use.

**Comment by nickv2002** [comment]
Hey @sumpfork does the image need to match pixel resolution of the other card header images (eg [Action Victory](https://github.com/sumpfork/dominiontabs/blob/master/images/action-victory_nc.png)) or can your code scale things appropriately?

**Comment by sumpfork** [comment]
It should scale, as far as I remember.
