### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by brgerig** [sumpfork/dominiontabs#64]
There is no open source or creative commons license specified, which technically means that the project, code, and resources fall under default restrictive copyright. I suspect based on your comments on the generator page, that you want it to be able to be used by others, but legally right now that can't be done without permission.

**Comment by sumpfork** [comment]
Hmm, I guess that's technically true, though the code did have a license when it got first published on launchpad (https://launchpad.net/dominiontabs, MIT / X / Expat Licence). Github doesn't force you to do this, so I guess updates since that are somewhat in limbo.

**Comment by sumpfork** [comment]
I added a license file that in addition to the MIT license also notes that I obtained non-transferable permission from Rio Grande Games to use the text/images from the games in this manner. https://github.com/sumpfork/dominiontabs/commit/259a22e4871f44409388286f4413d1684a6386f1
