### ISSUE TITLE
Rename Exclude Individual Events from Adventures

### ISSUE THREAD

**Issue by nickv2002** [sumpfork/dominiontabs#66]
_Exclude Individual Events from Adventures_ on the web interface should now read: _Exclude Individual Events from Adventures & Empires_ or maybe just _Exclude Individual Events_.

**Comment by nickv2002** [comment]
Or maybe just _Exclude Individual Events_

**Comment by nickv2002** [comment]
See also: making this option apply to Landmarks: https://github.com/sumpfork/dominiontabs/issues/67

**Comment by Bob-A-Mickelson** [comment]
Agreed.

**Comment by sumpfork** [comment]
Should be fixed online.
