### ISSUE TITLE
Exclude Individual Events should also apply to Landmarks

### ISSUE THREAD

**Issue by nickv2002** [sumpfork/dominiontabs#67]
Landmarks, like Events, are _1x_ cards that most people will want to group together.  I think the option we already have to group Events is sufficient (no need for a second option).  When this flag is toggled, only the Landmark group should be printed instead of dividers for each Landmark.

**Comment by Bob-A-Mickelson** [comment]
This is very much needed. As is I cannot print off the tabs without printing up tons of extra pages. Not sure why anone would want to sort landmarks by individual card name. Please make an option to print off a generic landmarks divider like adventures' events.

**Comment by sumpfork** [comment]
Acknowledged, will try to get to it asap

**Comment by davidjrawlings** [comment]
Agreed, this is essential for printing Empires tabs. Having them in also affects the left/right alternate, which makes it difficult to just throw away the unwanted prints of individual landmarks (tabs then don't alternate).

**Comment by sumpfork** [comment]
Should be fixed online.
