### ISSUE TITLE
Add option for Center Tab

### ISSUE THREAD

**Issue by a49ersfanatic** [sumpfork/dominiontabs#68]
Posted on Board Game Geek (thanks again):
This is a great tool. For something as simple and straightforward as dividers for a card game, you have gone way above and beyond and customized a way to satisfy all of us very picky and particular individuals.

I am a Python novice, so I must admit that the majority of code is beyond me. I've done my best to see if I can find the location of one minor detail in your divider generator, but I haven't had the luck. Even if I did, I'm not sure I'd be able to run the script.

Would it be possible to add an option for the tabs to be centered? They'd be the same size as tabs on the left or right, but centered, instead of full? A tiny detail compared to some of the more complex/useful issues your trying to solve, but I thought I'd ask.

Either way, this is a spectacular offering. Thank you.

**Comment by sumpfork** [comment]
I'm going to delay this until I look at https://github.com/sumpfork/dominiontabs/pull/65 as I know that that one touches the card outline quite a bit. Hopefully tomorrow?
