### ISSUE TITLE
Differnt Sorting

### ISSUE THREAD

**Issue by idlaviV** [sumpfork/dominiontabs#72]
In my opinion. one of the best features are the tabs on alternating sides, for better handling.
Though with alternating tabs, the order of the slides becomes relevant. They ordered alphabetically by default. It would be great to give the option to sort them first by expansion and then by pricepoint.
This would mirror the order in the standardbox.

**Comment by wvoigt** [comment]
Just for clarity, currently the sorting options are:

- **alphabetically**
- by **expansion**, then **alphabetically**

and you are asking for

- by **expansion**, then by **price point / cost**, then **alphabetically**

Do any other sorting options make sense?  Like:
- by **price point / cost**, then **alphabetically**

And on price point / cost,  What order should Potions and Debt come?
- separated into their own.  So Coins only, then Coins + Potions, then Debts
- mixed in. So all 1 coin, then all 1 coin + Potions, then all 1 Debts

**Comment by idlaviV** [comment]
Well, "**price point**, then **alphabetically**" might make sense, but I would not use it personally.
"**expansion**, then by **price point / cost**, then **alphabetically**" is the order in the dominion boxes (at least here in germany).

The potions are mixed in, but they are a different price than coins. 2P is more than 2, but not more than 3. However, 3 is not more than 2P. I would first sort cards by their coin-price, then by their potion/debt-cost. So its
0 - (1) - (2) - 1 - 1P - 1(1) - 1(2) - 1(3) - 2 - 2P - 2(1) etc.

**Comment by sumpfork** [comment]
Should be fixed with new deployment, please re-open if not.
