### ISSUE TITLE
Add set images for Sauna / Avanto

### ISSUE THREAD

**Issue by sumpfork** [sumpfork/dominiontabs#79]
#76 Added these, but there are not set images yet (see warning when running the script.)

**Comment by nickv2002** [comment]
The set image for this promo and all going forward is [the flag used on Summon](https://github.com/sumpfork/dominiontabs/blob/master/images/summon_set.png).

**Comment by nickv2002** [comment]
See fix here I think: https://github.com/sumpfork/dominiontabs/pull/80

Not sure why the pull includes all the stuff from yesterday that was already merged.

**Comment by nickv2002** [comment]
FWIW: the English Sauna / Avanto Promo is up on BGG store for USA Folks:
http://boardgamegeekstore.com/products/dominion-sauna-avanto
