### ISSUE TITLE
Incorrect card counts in Adventures and Empires

### ISSUE THREAD

**Issue by wvoigt** [sumpfork/dominiontabs#81]
Some of the card counts are not correct.  As a result, the sleeve/wrappers are not the correct size.

**Comment by mr-ice** [comment]
@wvoigt , I found counts are wrong on a few more empires split pile cards.

Hermit, Madman, Urchin, Mercenary, Sauna, Avanto, Sauna / Avanto

I had to set Sauna / Avanto to count: 0 else it printed out a wrapper that was 20 cards deep.  

This matched Patrician / Emporium (0) which renders correctly.

However Settlers / Bustling Village renders correctly and is set to 10 (and each constituent card is set to 5).  I haven't dug into that more.

`--- a/card_db/en_us/cards.json
+++ b/card_db/en_us/cards.json
@@ -1590,6 +1590,7 @@
   "extra": "Sauna is a promotional Action card. It's a cantrip that allows you to trash a card when you play a Silver. It is a split pile card, with five copies of Sauna sitting on top of five copies of Avanto.",
   "name": "Sauna",
   "potcost": 0,
+  "count": 5,
   "types":[
    "Action"
   ]
@@ -1601,6 +1602,7 @@
   "extra": "Avanto is a promotional Action card. It's a terminal draw card that can potentially become non-terminal if you have a Sauna in your hand to play. It is a split pile card, with five copies of Avanto sitting under five copies of Sauna.",
   "name": "Avanto",
   "potcost": 0,
+  "count": 5,
   "types":[
    "Action"
   ]
@@ -1612,6 +1614,7 @@
   "extra": "Sauna \/ Avanto is a split pile with five copies of Sauna placed on top of five copies of Avanto during setup. Sauna is a cantrip that allows you to trash a card when you play a Silver. Avanto is a terminal draw card that can potentially become non-terminal if you have a Sauna in your hand to play.",
   "name": "Sauna \/ Avanto",
   "potcost": 0,
+  "count": 0,
   "types":[
    "Action"
   ]
`

**Comment by wvoigt** [comment]
@mr-ice  I understand the Sauna, Avanto, Sauna / Avanto since I did not have those.

What is wrong with Hermit, Madman, Urchin, Mercenary?  Mine printed 10 each individually, or 20 when paired Hermit / Madman and Urchin / Mercenary.  By type, their counts should default to 10 each.

I believe the Settlers / Bustling Village should be set to 0 for consistency.  But for some reason that doesn't work.  Must be a bug.   I'll see if I can track it down.

**Comment by wvoigt** [comment]
Reopening until we figure out the Settlers / Bustling Village issue.

**Comment by mr-ice** [comment]
> What is wrong with Hermit, Madman, Urchin, Mercenary?

Bad assumptions.  

I looked closer and it was correct.  I admit I didn't print them, just thought they looked strange as a 20 wrapper and assumed they were like the other 5/5 stacks -- however 10 is more correct (I need to futz with wrappers less and play more, obviously).

**Comment by mr-ice** [comment]
Settlers / Bustling Village is in card_groups.json as Bustling Village / Settlers.
